// Phase 4b — Lock-to-source, Path B (hand-authored JSX/TSX patch).
//
// Spec: planning/2026-05-18-inspector-direct-manipulation-roadmap.md,
//       "Phase 4b — Path B (JSX/TSX AST patch via element
//       instrumentation)". GitHub issue #1308.
//
// These tests prove the contract the roadmap calls for:
//   tweak (anchor_id → property_path → value)
//     → jsx_lock_tweak_into_source
//     → the authored JSX/TSX now carries the new value at the right span
//     → every other byte (prose, comments, formatting) is preserved.
//
// Scope is Path B only — *hand-authored* JSX/TSX, located by the
// `data-pulp-anchor` instrumentation attribute. Path A (generated
// web-compat JS) and Path C (DESIGN.md tokens) are out of scope here.

#include <catch2/catch_test_macros.hpp>

#include <pulp/view/jsx_lock.hpp>

#include <string>

using namespace pulp::view;

namespace {

// A small hand-authored TSX panel with two instrumented elements: a
// frame with an inline style object, and a Knob with bare-attribute and
// expression-container props.
const char* kPanelTsx = R"TSX(// MyPanel.tsx — hand-authored instrument UI.
// The padding here was tuned by hand; keep this comment.
import { Knob, Frame } from '@pulp/react';

export const MyPanel = () => (
  <Frame
    data-pulp-anchor="sha1:frame-root"
    style={{ padding: 8, background: '#222222', gap: 4 }}
  >
    <Knob
      data-pulp-anchor="sha1:knob-gain"
      label="Gain"
      width={80}
      color="#888888"
      style={{ borderRadius: 4, opacity: 1 }}
    />
  </Frame>
);
)TSX";

}  // namespace

// ── Property-path mapping ───────────────────────────────────────────────

TEST_CASE("jsx_lock_property_to_key maps dotted paths", "[jsx-lock][issue-1308]") {
    REQUIRE(jsx_lock_property_to_key("paint.backgroundColor") == "backgroundColor");
    REQUIRE(jsx_lock_property_to_key("style.width") == "width");
    REQUIRE(jsx_lock_property_to_key("layout.padding") == "padding");
    REQUIRE(jsx_lock_property_to_key("paint.background-color") == "backgroundColor");
    REQUIRE(jsx_lock_property_to_key("layout.padding_top") == "paddingTop");
    REQUIRE(jsx_lock_property_to_key("width") == "width");

    SECTION("rejections") {
        REQUIRE_FALSE(jsx_lock_property_to_key("audio.gain").has_value());
        REQUIRE_FALSE(jsx_lock_property_to_key("paint.unicornHorn").has_value());
        REQUIRE_FALSE(jsx_lock_property_to_key("layout.padding.top").has_value());
        REQUIRE_FALSE(jsx_lock_property_to_key("   ").has_value());
    }
}

// ── Authored-vs-generated detection ─────────────────────────────────────

TEST_CASE("is_authored_jsx_source distinguishes authored JSX from generated",
          "[jsx-lock][issue-1308]") {
    REQUIRE(is_authored_jsx_source(kPanelTsx));
    REQUIRE(is_authored_jsx_source("export const A = () => <div/>;\n"));

    SECTION("a generated artifact is rejected") {
        REQUIRE_FALSE(is_authored_jsx_source(
            "// Generated by Pulp import-design from panel.fig\n"
            "const x = document.createElement('div');\n"));
        REQUIRE_FALSE(is_authored_jsx_source(
            "// @generated\n<div/>\n"));
    }
    SECTION("plain non-JSX text is not authored JSX") {
        REQUIRE_FALSE(is_authored_jsx_source("const x = 1;\nconst y = 2;\n"));
    }
}

// ── Patch a property inside an inline style object ──────────────────────

TEST_CASE("jsx_lock patches a style-object property by anchor",
          "[jsx-lock][issue-1308]") {
    JsxLockTweak tweak{"sha1:frame-root", "layout.padding", "16"};
    JsxLockResult r = jsx_lock_tweak_into_source(kPanelTsx, tweak);

    REQUIRE(r.status == JsxLockStatus::patched);
    REQUIRE(r.ok());
    REQUIRE(r.mutated());
    REQUIRE(r.property == "padding");
    REQUIRE(r.line > 0);
    // The numeric literal was rewritten in place; the unit-less number
    // stays a bare JS number.
    REQUIRE(r.source.find("padding: 16,") != std::string::npos);
    REQUIRE(r.source.find("padding: 8,") == std::string::npos);
    // Sibling properties are untouched.
    REQUIRE(r.source.find("background: '#222222'") != std::string::npos);
    REQUIRE(r.source.find("gap: 4") != std::string::npos);
}

TEST_CASE("jsx_lock patches a quoted style-object string value",
          "[jsx-lock][issue-1308]") {
    JsxLockTweak tweak{"sha1:frame-root", "paint.background", "#5a5a5a"};
    JsxLockResult r = jsx_lock_tweak_into_source(kPanelTsx, tweak);

    REQUIRE(r.status == JsxLockStatus::patched);
    REQUIRE(r.source.find("background: '#5a5a5a'") != std::string::npos);
    REQUIRE(r.source.find("'#222222'") == std::string::npos);
}

// ── Patch a bare attribute ──────────────────────────────────────────────

TEST_CASE("jsx_lock patches a bare quoted attribute", "[jsx-lock][issue-1308]") {
    JsxLockTweak tweak{"sha1:knob-gain", "paint.color", "#5a5a5a"};
    JsxLockResult r = jsx_lock_tweak_into_source(kPanelTsx, tweak);

    REQUIRE(r.status == JsxLockStatus::patched);
    REQUIRE(r.property == "color");
    REQUIRE(r.source.find("color=\"#5a5a5a\"") != std::string::npos);
    REQUIRE(r.source.find("color=\"#888888\"") == std::string::npos);
}

TEST_CASE("jsx_lock patches a bare numeric expression-container attribute",
          "[jsx-lock][issue-1308]") {
    JsxLockTweak tweak{"sha1:knob-gain", "style.width", "120"};
    JsxLockResult r = jsx_lock_tweak_into_source(kPanelTsx, tweak);

    REQUIRE(r.status == JsxLockStatus::patched);
    REQUIRE(r.property == "width");
    REQUIRE(r.source.find("width={120}") != std::string::npos);
    REQUIRE(r.source.find("width={80}") == std::string::npos);
}

// ── Formatting preservation ─────────────────────────────────────────────

TEST_CASE("jsx_lock preserves every other byte of the source",
          "[jsx-lock][issue-1308]") {
    JsxLockTweak tweak{"sha1:knob-gain", "paint.borderRadius", "8"};
    JsxLockResult r = jsx_lock_tweak_into_source(kPanelTsx, tweak);

    REQUIRE(r.status == JsxLockStatus::patched);
    // The hand-written comments and imports survive verbatim.
    REQUIRE(r.source.find("// MyPanel.tsx — hand-authored instrument UI.")
            != std::string::npos);
    REQUIRE(r.source.find("// The padding here was tuned by hand; keep this comment.")
            != std::string::npos);
    REQUIRE(r.source.find("import { Knob, Frame } from '@pulp/react';")
            != std::string::npos);

    // The patch is exactly one span: source length differs only by the
    // literal width delta ("4" -> "8" is same length here).
    REQUIRE(r.source.size() == std::string(kPanelTsx).size());
    REQUIRE(r.source.find("borderRadius: 8") != std::string::npos);
    REQUIRE(r.source.find("opacity: 1") != std::string::npos);  // sibling kept.
}

// ── Idempotent re-lock ──────────────────────────────────────────────────

TEST_CASE("jsx_lock is idempotent when the value is already current",
          "[jsx-lock][issue-1308]") {
    JsxLockTweak tweak{"sha1:frame-root", "layout.padding", "24"};
    JsxLockResult first = jsx_lock_tweak_into_source(kPanelTsx, tweak);
    REQUIRE(first.status == JsxLockStatus::patched);

    JsxLockResult second = jsx_lock_tweak_into_source(first.source, tweak);
    REQUIRE(second.status == JsxLockStatus::already_current);
    REQUIRE(second.ok());
    REQUIRE_FALSE(second.mutated());
    REQUIRE(second.source == first.source);  // byte-identical, no churn.
}

// ── Anchor-not-found graceful failure ───────────────────────────────────

TEST_CASE("jsx_lock fails gracefully on an unknown anchor",
          "[jsx-lock][issue-1308]") {
    JsxLockTweak tweak{"sha1:does-not-exist", "paint.background", "#000000"};
    JsxLockResult r = jsx_lock_tweak_into_source(kPanelTsx, tweak);

    REQUIRE(r.status == JsxLockStatus::anchor_not_found);
    REQUIRE_FALSE(r.ok());
    REQUIRE_FALSE(r.mutated());
    REQUIRE(r.line == 0);
    REQUIRE(r.source == kPanelTsx);  // source untouched.
    REQUIRE_FALSE(r.message.empty());
}

TEST_CASE("jsx_lock rejects an empty anchor id", "[jsx-lock][issue-1308]") {
    JsxLockResult r = jsx_lock_tweak_into_source(
        kPanelTsx, {"", "paint.background", "#000000"});
    REQUIRE(r.status == JsxLockStatus::anchor_not_found);
    REQUIRE(r.source == kPanelTsx);
}

// ── Ambiguous anchor — refuse to guess ──────────────────────────────────

TEST_CASE("jsx_lock refuses to patch a duplicated anchor",
          "[jsx-lock][issue-1308]") {
    const std::string dup =
        "<Frame data-pulp-anchor=\"dup\" style={{ padding: 1 }}/>\n"
        "<Frame data-pulp-anchor=\"dup\" style={{ padding: 2 }}/>\n";
    JsxLockResult r = jsx_lock_tweak_into_source(
        dup, {"dup", "layout.padding", "9"});

    REQUIRE(r.status == JsxLockStatus::anchor_ambiguous);
    REQUIRE_FALSE(r.ok());
    REQUIRE(r.source == dup);  // source untouched.
}

// ── Unsupported property path ───────────────────────────────────────────

TEST_CASE("jsx_lock rejects an unsupported property path",
          "[jsx-lock][issue-1308]") {
    JsxLockResult r = jsx_lock_tweak_into_source(
        kPanelTsx, {"sha1:knob-gain", "audio.gain", "0.8"});

    REQUIRE(r.status == JsxLockStatus::unsupported_property);
    REQUIRE_FALSE(r.ok());
    REQUIRE(r.source == kPanelTsx);  // source untouched.
    REQUIRE(r.property.empty());
}

// ── Too-dynamic: non-literal value stays in the sidecar ─────────────────

TEST_CASE("jsx_lock refuses a non-literal style-property value",
          "[jsx-lock][issue-1308]") {
    const std::string dyn =
        "<Frame data-pulp-anchor=\"a\" style={{ padding: gap * 2 }}/>\n";
    JsxLockResult r = jsx_lock_tweak_into_source(
        dyn, {"a", "layout.padding", "16"});

    REQUIRE(r.status == JsxLockStatus::too_dynamic);
    REQUIRE_FALSE(r.ok());
    REQUIRE(r.source == dyn);  // source untouched.
    REQUIRE(r.message.find("non-literal") != std::string::npos);
}

TEST_CASE("jsx_lock refuses a style object that uses a spread",
          "[jsx-lock][issue-1308]") {
    const std::string spread =
        "<Frame data-pulp-anchor=\"a\" style={{ ...base, padding: 8 }}/>\n";
    JsxLockResult r = jsx_lock_tweak_into_source(
        spread, {"a", "layout.padding", "16"});

    REQUIRE(r.status == JsxLockStatus::too_dynamic);
    REQUIRE(r.source == spread);  // source untouched.
    REQUIRE(r.message.find("spread") != std::string::npos);
}

TEST_CASE("jsx_lock refuses a non-literal expression-container attribute",
          "[jsx-lock][issue-1308]") {
    const std::string dyn =
        "<Knob data-pulp-anchor=\"a\" width={baseWidth}/>\n";
    JsxLockResult r = jsx_lock_tweak_into_source(
        dyn, {"a", "style.width", "120"});

    REQUIRE(r.status == JsxLockStatus::too_dynamic);
    REQUIRE(r.source == dyn);  // source untouched.
}

TEST_CASE("jsx_lock refuses a style prop bound to a variable",
          "[jsx-lock][issue-1308]") {
    const std::string dyn =
        "<Frame data-pulp-anchor=\"a\" style={panelStyle}/>\n";
    JsxLockResult r = jsx_lock_tweak_into_source(
        dyn, {"a", "layout.padding", "16"});

    REQUIRE(r.status == JsxLockStatus::too_dynamic);
    REQUIRE(r.source == dyn);  // source untouched.
}

// ── Missing prop on a located element — patch existing props only ───────

TEST_CASE("jsx_lock will not insert a prop the author never wrote",
          "[jsx-lock][issue-1308]") {
    // The frame has no `color` style property or attribute.
    JsxLockResult r = jsx_lock_tweak_into_source(
        kPanelTsx, {"sha1:frame-root", "paint.color", "#fff"});

    REQUIRE(r.status == JsxLockStatus::too_dynamic);
    REQUIRE_FALSE(r.ok());
    REQUIRE(r.source == kPanelTsx);  // source untouched.
}

// ── Value escaping (a value with a quote must not break the JSX) ────────

TEST_CASE("jsx_lock escapes single quotes in a string value",
          "[jsx-lock][issue-1308]") {
    const std::string src =
        "<Frame data-pulp-anchor=\"a\" style={{ fontFamily: 'Inter' }}/>\n";
    JsxLockResult r = jsx_lock_tweak_into_source(
        src, {"a", "paint.fontFamily", "Mike's Font"});

    REQUIRE(r.status == JsxLockStatus::patched);
    REQUIRE(r.source.find("Mike\\'s Font") != std::string::npos);
}

TEST_CASE("jsx_lock escapes double quotes in double-quoted values",
          "[jsx-lock][issue-1308]") {
    const std::string style_src =
        "<Frame data-pulp-anchor=\"a\" style={{ fontFamily: \"Inter\" }}/>\n";
    JsxLockResult style = jsx_lock_tweak_into_source(
        style_src, {"a", "paint.fontFamily", "Quote \" Font"});

    REQUIRE(style.status == JsxLockStatus::patched);
    REQUIRE(style.source.find("fontFamily: \"Quote \\\" Font\"") !=
            std::string::npos);

    const std::string attr_src =
        "<Knob data-pulp-anchor=\"a\" color=\"old\"/>\n";
    JsxLockResult attr = jsx_lock_tweak_into_source(
        attr_src, {"a", "paint.color", "he said \"blue\""});

    REQUIRE(attr.status == JsxLockStatus::patched);
    REQUIRE(attr.source.find("color=\"he said \\\"blue\\\"\"") !=
            std::string::npos);
}

TEST_CASE("jsx_lock escapes JS control characters in string values",
          "[jsx-lock][issue-1308][issue-2470]") {
    const std::string src =
        "<Frame data-pulp-anchor=\"a\" style={{ fontFamily: 'Inter' }}/>\n";
    std::string value = "Line\nTab\tCarriage\r";
    value.push_back(static_cast<char>(0x1F));
    value += "Slash\\Quote'";

    JsxLockResult r = jsx_lock_tweak_into_source(
        src, {"a", "paint.fontFamily", value});

    REQUIRE(r.status == JsxLockStatus::patched);
    REQUIRE(r.source.find(
        "fontFamily: 'Line\\nTab\\tCarriage\\r\\x1FSlash\\\\Quote\\''") !=
        std::string::npos);
    REQUIRE(r.source.find("Line\nTab") == std::string::npos);
}

TEST_CASE("jsx_lock converts a numeric prop to a quoted string when needed",
          "[jsx-lock][issue-1308]") {
    // width={80} (bare number) tweaked to a unit-bearing CSS value must
    // become a quoted string so the JS stays valid.
    const std::string src =
        "<Knob data-pulp-anchor=\"a\" width={80}/>\n";
    JsxLockResult r = jsx_lock_tweak_into_source(
        src, {"a", "style.width", "120px"});

    REQUIRE(r.status == JsxLockStatus::patched);
    REQUIRE(r.source.find("width={'120px'}") != std::string::npos);
}

// ── Multi-tweak pass ────────────────────────────────────────────────────

TEST_CASE("jsx_lock_tweaks_into_source applies several tweaks in one pass",
          "[jsx-lock][issue-1308]") {
    std::vector<JsxLockTweak> tweaks{
        {"sha1:frame-root", "layout.padding", "16"},
        {"sha1:knob-gain", "paint.color", "#5a5a5a"},
        {"sha1:knob-gain", "style.width", "120"},
    };
    auto results = jsx_lock_tweaks_into_source(kPanelTsx, tweaks);

    REQUIRE(results.size() == 3);
    for (const auto& r : results) REQUIRE(r.status == JsxLockStatus::patched);

    const std::string& final = results.back().source;
    for (const auto& r : results) REQUIRE(r.source == final);
    REQUIRE(final.find("padding: 16,") != std::string::npos);
    REQUIRE(final.find("color=\"#5a5a5a\"") != std::string::npos);
    REQUIRE(final.find("width={120}") != std::string::npos);
}
