//! Generate `cmake/pulp-packages.cmake` from the lock file + registry.
//!
//! # Scope
//!
//! This module is a *pure* renderer — it doesn't touch the filesystem
//! itself. The C++ reference lives in `package_commands.cpp::
//! generate_packages_cmake` and `generate_cmake_block`.
//!
//! # Output shape
//!
//! ```cmake
//! # Auto-generated by pulp package manager — do not edit manually
//! # Run 'pulp add <pkg>' or 'pulp remove <pkg>' to modify
//! include(FetchContent)
//!
//! # ── alac (master) ──
//! FetchContent_Declare(alac
//!   GIT_REPOSITORY https://github.com/macosforge/alac.git
//!   GIT_TAG        master
//!   GIT_SHALLOW    TRUE
//! )
//! FetchContent_MakeAvailable(alac)
//! # ── end alac ──
//! ```
//!
//! Header-only packages declare an INTERFACE target and
//! `target_include_directories` the fetched source.

use crate::pkg::registry::{LockFile, PackageDescriptor, Registry};

/// Render `cmake/pulp-packages.cmake` from `lock` + `reg`.
///
/// Packages in the lock file that aren't in the registry are skipped
/// (matches C++ behaviour). Ordering follows the lock file's
/// `BTreeMap` natural order — alphabetical by id.
#[must_use]
pub fn generate_packages_cmake(lock: &LockFile, reg: &Registry) -> String {
    let mut out = String::new();
    out.push_str("# Auto-generated by pulp package manager — do not edit manually\n");
    out.push_str("# Run 'pulp add <pkg>' or 'pulp remove <pkg>' to modify\n");
    out.push_str("include(FetchContent)\n\n");
    for id in lock.packages.keys() {
        let Some(pkg) = reg.packages.get(id) else {
            continue;
        };
        out.push_str(&generate_block(pkg, None));
        out.push('\n');
    }
    out
}

/// Render a single `FetchContent` block for `pkg`.
///
/// When `guard_platform` is `Some("macOS")` / `"Windows"` / `"Linux"`,
/// the block is wrapped in the matching `if(APPLE)` / `if(WIN32)` /
/// `if(UNIX AND NOT APPLE)` guard and gets a
/// `target_compile_definitions(... PULP_HAS_<ID>=1)` flag.
#[must_use]
pub fn generate_block(pkg: &PackageDescriptor, guard_platform: Option<&str>) -> String {
    use std::fmt::Write as _;
    let guarded = guard_platform.is_some();
    let indent = if guarded { "  " } else { "" };
    let mut out = String::new();
    let _ = write!(out, "# ── {} ({}) ", pkg.id, pkg.version);
    if let Some(p) = guard_platform {
        let _ = write!(out, "[{p} only] ");
    }
    out.push_str("──\n");

    if let Some(p) = guard_platform {
        match p {
            "macOS" => out.push_str("if(APPLE)\n"),
            "Windows" => out.push_str("if(WIN32)\n"),
            "Linux" => out.push_str("if(UNIX AND NOT APPLE)\n"),
            _ => {}
        }
    }

    out.push_str(indent);
    let _ = writeln!(out, "FetchContent_Declare({}", pkg.id);
    out.push_str(indent);
    let _ = writeln!(out, "  GIT_REPOSITORY {}", pkg.fetch.git_repository);
    out.push_str(indent);
    let _ = writeln!(out, "  GIT_TAG        {}", pkg.fetch.git_tag);
    out.push_str(indent);
    out.push_str("  GIT_SHALLOW    TRUE\n");
    out.push_str(indent);
    out.push_str(")\n");
    out.push_str(indent);
    let _ = writeln!(out, "FetchContent_MakeAvailable({})", pkg.id);

    if pkg.fetch.method == "header-only" {
        if let Some(target) = pkg.cmake.targets.first() {
            out.push_str(indent);
            let _ = writeln!(out, "add_library({target} INTERFACE)");
            out.push_str(indent);
            let _ = write!(
                out,
                "target_include_directories({} INTERFACE ${{{}_SOURCE_DIR}}",
                target, pkg.id
            );
            if !pkg.cmake.include_dir.is_empty() && pkg.cmake.include_dir != "." {
                out.push('/');
                out.push_str(&pkg.cmake.include_dir);
            }
            out.push_str(")\n");
        }
    }

    if guarded {
        let upper = pkg
            .id
            .chars()
            .map(|c| {
                if c == '-' {
                    '_'
                } else {
                    c.to_ascii_uppercase()
                }
            })
            .collect::<String>();
        let _ = writeln!(
            out,
            "  target_compile_definitions(${{PROJECT_NAME}} PRIVATE PULP_HAS_{upper}=1)"
        );
        out.push_str("endif()\n");
    }

    let _ = writeln!(out, "# ── end {} ──", pkg.id);
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pkg::registry::{CMakeInfo, FetchInfo, LockedPackage};
    use std::collections::BTreeMap;

    fn alac_pkg() -> PackageDescriptor {
        PackageDescriptor {
            id: "alac".to_owned(),
            name: "Apple ALAC".to_owned(),
            version: "master".to_owned(),
            fetch: FetchInfo {
                method: "FetchContent".to_owned(),
                git_repository: "https://example.com/alac.git".to_owned(),
                git_tag: "master".to_owned(),
            },
            cmake: CMakeInfo {
                targets: vec!["alac".to_owned()],
                header_only: false,
                include_dir: String::new(),
            },
            ..PackageDescriptor::default()
        }
    }

    #[test]
    fn block_renders_fetchcontent_declare_and_makeavailable() {
        let pkg = alac_pkg();
        let s = generate_block(&pkg, None);
        assert!(s.contains("FetchContent_Declare(alac"));
        assert!(s.contains("GIT_REPOSITORY https://example.com/alac.git"));
        assert!(s.contains("GIT_TAG        master"));
        assert!(s.contains("GIT_SHALLOW    TRUE"));
        assert!(s.contains("FetchContent_MakeAvailable(alac)"));
        assert!(s.contains("# ── end alac ──"));
    }

    #[test]
    fn block_with_macos_guard_wraps_in_apple_if() {
        let pkg = alac_pkg();
        let s = generate_block(&pkg, Some("macOS"));
        assert!(s.contains("if(APPLE)"));
        assert!(s.contains("endif()"));
        assert!(s.contains("PULP_HAS_ALAC=1"));
    }

    #[test]
    fn block_with_header_only_fetch_adds_interface_target() {
        let mut pkg = alac_pkg();
        pkg.fetch.method = "header-only".to_owned();
        pkg.cmake.include_dir = "include".to_owned();
        let s = generate_block(&pkg, None);
        assert!(s.contains("add_library(alac INTERFACE)"));
        assert!(s.contains("target_include_directories(alac INTERFACE ${alac_SOURCE_DIR}/include)"));
    }

    #[test]
    fn generator_skips_packages_not_in_registry() {
        let mut lock = LockFile::default();
        lock.packages.insert(
            "ghost".to_owned(),
            LockedPackage {
                version: "1.0".to_owned(),
                ..LockedPackage::default()
            },
        );
        let reg = Registry {
            version: 1,
            packages: BTreeMap::new(),
        };
        let s = generate_packages_cmake(&lock, &reg);
        // Header + include line present but no FetchContent block.
        assert!(s.contains("include(FetchContent)"));
        assert!(!s.contains("ghost"));
    }

    #[test]
    fn guarded_id_with_dash_is_uppercased_and_underscored() {
        let mut pkg = alac_pkg();
        pkg.id = "foo-bar".to_owned();
        let s = generate_block(&pkg, Some("Windows"));
        assert!(s.contains("PULP_HAS_FOO_BAR=1"));
    }
}
