#!/usr/bin/env python3
"""Reject commits/pushes that include known CLI test-fixture corruption.

PR #1755 (object-fit) accidentally shipped a 977-line CMakeLists.txt
overwritten by a 3-line "Clock" CLI test fixture, plus a pulp.toml with
a `/private/var/folders/.../pulp-shellout-...` sdk_path. Required hotfix
PR #1757 to restore CI. This script blocks the same regression from
landing again, regardless of whether the corruption originated from a
flaky CLI test, a manual `pulp project bump` in the wrong cwd, or a
shipyard auto-commit.

Patterns blocked at repo root:
  * CMakeLists.txt containing `project(Clock VERSION 1.0.0` —
    that's the exact signature `test_cli_shellout.cpp:1605-1624`
    writes into its temp Clock fixture.
  * pulp.toml — never belongs in the source tree; it is a per-developer
    per-project SDK pin file, generated by `pulp project init`.

Patterns warned about (non-blocking):
  * Any tracked file path containing `/private/var/folders/` or
    `pulp-shellout-` (likely test-fixture leakage even if the file
    isn't one of the two above).

Modes:
  --mode=stage    inspect `git diff --cached` (pre-commit). Default.
  --mode=push     inspect `BASE...HEAD` (pre-push).
  --mode=files    inspect explicit file list passed positionally
                  (CI workflow use — pass the PR diff file list).

Exit codes:
  0  no pollution detected
  1  pollution detected — push/commit blocked (stderr names the file)
  2  invocation error
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

CLOCK_FIXTURE_SIGNATURE = "project(Clock VERSION 1.0.0"
PULP_PROJECT_SIGNATURE = "project(Pulp"
TEMP_FIXTURE_PATH_HINTS = ("/private/var/folders/", "pulp-shellout-")


def _git_diff_files(rev_range: str | None, mode: str) -> list[str]:
    if mode == "stage":
        cmd = ["git", "diff", "--cached", "--name-only"]
    elif mode == "push":
        if not rev_range:
            return []
        cmd = ["git", "diff", "--name-only", rev_range]
    else:
        return []
    out = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if out.returncode != 0:
        return []
    return [line.strip() for line in out.stdout.splitlines() if line.strip()]


def _read_blob(rev: str | None, path: str) -> str:
    """Read file content. For staged mode, read from the index. For push mode,
    read from HEAD. For files mode, read from the working tree."""
    if rev:
        out = subprocess.run(
            ["git", "show", f"{rev}:{path}"],
            capture_output=True, text=True, check=False,
        )
        if out.returncode == 0:
            return out.stdout
        return ""
    p = Path(path)
    if p.is_file():
        try:
            return p.read_text(errors="replace")
        except OSError:
            return ""
    return ""


def check(files: list[str], rev: str | None) -> tuple[list[str], list[str]]:
    """Return (errors, warnings)."""
    errors: list[str] = []
    warnings: list[str] = []
    for path in files:
        # Block #1 — pulp.toml at repo root is always wrong.
        if path == "pulp.toml":
            errors.append(
                f"  {path}: pulp.toml must never be in the source tree. "
                "It's a per-developer/per-project SDK pin generated by "
                "`pulp project init` and should be in .gitignore. The most "
                "likely cause is a CLI test (test_cli_shellout.cpp) that "
                "left a /tmp Clock fixture in the working dir, or a manual "
                "`pulp project bump` ran in the source tree. Delete the "
                "file (`git rm pulp.toml`) and re-stage."
            )
            continue
        # Block #2 — CMakeLists.txt at repo root must declare project(Pulp.
        # Two-pronged check: explicit Clock-fixture signature catches the
        # known #1755 case with a precise error message; positive
        # `project(Pulp` assertion catches ANY future fixture / unrelated
        # CMakeLists.txt being committed at the root (the parallel agent's
        # broader proposal — e.g. somebody pastes an `examples/foo`
        # CMakeLists.txt at the root accidentally).
        if path == "CMakeLists.txt":
            content = _read_blob(rev, path)
            if CLOCK_FIXTURE_SIGNATURE in content:
                errors.append(
                    f"  {path}: contains `project(Clock VERSION 1.0.0` — "
                    "this is the exact signature of the temp CLI test "
                    "fixture from test_cli_shellout.cpp:1605-1624. The "
                    "real Pulp CMakeLists.txt is ~977 lines and starts "
                    "with `project(Pulp VERSION ...`. Restore it from "
                    "main: `git show origin/main:CMakeLists.txt > CMakeLists.txt`. "
                    "PR #1755 accidentally shipped this corruption; #1757 "
                    "was the hotfix; this guard prevents a repeat."
                )
                continue
            # Positive assertion — first ~10 lines must contain
            # `project(Pulp`. Catches any non-Pulp CMakeLists.txt at the
            # root regardless of the specific fixture, including future
            # examples/foo/CMakeLists.txt accidents.
            head = "\n".join(content.splitlines()[:10])
            if content.strip() and PULP_PROJECT_SIGNATURE not in head:
                errors.append(
                    f"  {path}: first 10 lines do not contain "
                    f"`{PULP_PROJECT_SIGNATURE}`. The root CMakeLists.txt "
                    "must declare `project(Pulp ...)` — anything else is "
                    "almost certainly an example or fixture file pasted "
                    "into the wrong place. If you genuinely intended to "
                    "rename the project, update both this guard and the "
                    "test in tools/scripts/test_source_tree_pollution_check.py."
                )
                continue
        # Warn — paths that look like test-fixture leakage.
        for hint in TEMP_FIXTURE_PATH_HINTS:
            if hint in path:
                warnings.append(
                    f"  {path}: path contains `{hint}` which suggests CLI "
                    "test-fixture leakage. Confirm this file actually "
                    "belongs in the repo (it is rare for source files to "
                    "have temp-dir paths in them)."
                )
    return errors, warnings


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--mode", choices=("stage", "push", "files"),
                        default="stage")
    parser.add_argument("--base", default="origin/main",
                        help="for --mode=push, base ref (default origin/main)")
    parser.add_argument("files", nargs="*",
                        help="for --mode=files, explicit file list")
    args = parser.parse_args(argv)

    if args.mode == "stage":
        files = _git_diff_files(None, "stage")
        rev = None
    elif args.mode == "push":
        files = _git_diff_files(f"{args.base}...HEAD", "push")
        rev = "HEAD"
    elif args.mode == "files":
        files = args.files
        rev = None
    else:
        sys.stderr.write(f"unknown mode: {args.mode}\n")
        return 2

    errors, warnings = check(files, rev)

    if warnings:
        sys.stderr.write("[source-tree-pollution] warnings:\n")
        for w in warnings:
            sys.stderr.write(w + "\n")

    if errors:
        sys.stderr.write("[source-tree-pollution] BLOCKED:\n")
        for e in errors:
            sys.stderr.write(e + "\n")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
