#!/usr/bin/env python3
"""Reject commits/pushes that include known CLI test-fixture corruption.

PR #1755 (object-fit) accidentally shipped a 977-line CMakeLists.txt
overwritten by a 3-line "Clock" CLI test fixture, plus a pulp.toml with
a `/private/var/folders/.../pulp-shellout-...` sdk_path. Required hotfix
PR #1757 to restore CI. This script blocks the same regression from
landing again, regardless of whether the corruption originated from a
flaky CLI test, a manual `pulp project bump` in the wrong cwd, or a
shipyard auto-commit.

Patterns blocked at repo root:
  * CMakeLists.txt containing `project(Clock VERSION 1.0.0` —
    that's the exact signature `test_cli_shellout.cpp:1605-1624`
    writes into its temp Clock fixture.
  * pulp.toml — never belongs in the source tree; it is a per-developer
    per-project SDK pin file, generated by `pulp project init`.

Patterns warned about (non-blocking):
  * Any tracked file path containing `/private/var/folders/` or
    `pulp-shellout-` (likely test-fixture leakage even if the file
    isn't one of the two above).

Modes:
  --mode=stage           inspect `git diff --cached` (pre-commit). Default.
  --mode=push            inspect `BASE...HEAD` (pre-push).
  --mode=files           inspect explicit file list passed positionally
                         (CI workflow use — pass the PR diff file list).
  --mode=root-allowlist  inspect top-level paths on `--rev` (default HEAD)
                         and fail if any are not in ALLOWED_ROOT_PATHS.
                         Companion-track U-1 — see
                         planning/2026-05-17-refactor-roadmap-final.md.

Exit codes:
  0  no pollution detected
  1  pollution detected — push/commit blocked (stderr names the file)
  2  invocation error
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

CLOCK_FIXTURE_SIGNATURE = "project(Clock VERSION 1.0.0"
# pulp #1763 (Codex P2 followup) — case-insensitive `project(Pulp`
# matcher. CMake command names are case-insensitive and allow
# whitespace before `(`, so `PROJECT(Pulp...)` and `project (Pulp...)`
# are valid. Substring match was too strict; use a regex.
PULP_PROJECT_PATTERN = re.compile(r"\bproject\s*\(\s*Pulp\b", re.IGNORECASE)
TEMP_FIXTURE_PATH_HINTS = ("/private/var/folders/", "pulp-shellout-")

# Companion-track U-1 (planning/2026-05-17-refactor-roadmap-final.md):
# Allowlist of legitimate top-level repo entries. Used by
# --mode=root-allowlist to fail when an unexpected top-level path
# appears, which is almost always either a stray temp/test artifact
# or a mis-placed module that should live under a subdirectory.
#
# To add a new top-level entry: add it here in the same PR, with a
# brief comment if the reason isn't obvious from the name.
ALLOWED_ROOT_PATHS = frozenset({
    # Hidden config / metadata
    ".agents",
    ".claude",
    ".claude-plugin",
    ".clang-format",
    ".gitattributes",
    ".githooks",
    ".github",
    ".gitignore",
    ".gitmodules",
    ".iwyu-mappings.imp",
    ".mcp.json",
    ".shipyard",
    ".shipyard.local",
    ".status-ladder-waivers.txt",
    # Top-level docs
    "AGENTS.md",
    "CHANGELOG.md",
    "CLAUDE.md",
    "CONTRIBUTING.md",
    "DEPENDENCIES.md",
    "LICENSE.md",
    "NOTICE.md",
    "README.md",
    "VISION.md",
    # Top-level build / config
    "CMakeLists.txt",
    "codecov.yml",
    "compat.json",
    "config.example.toml",
    "mkdocs.yml",
    "requirements-docs.txt",
    "setup.ps1",
    "setup.sh",
    "validate-build.ps1",
    "validate-build.sh",
    # Top-level subsystem dirs
    "android",
    "apple",
    "bindings",
    "ci",
    "core",
    "docs",
    "examples",
    "experimental",
    "external",
    "hooks",
    "inspect",
    "packages",
    "planning",
    "scripts",
    "ship",
    "templates",
    "test",
    "tools",
})


# Sentinel returned by _git_diff_files when the diff itself failed.
# Distinguishes "no changed files" (empty list) from "git diff couldn't
# run" — the latter must fail closed per Codex P1 finding on #1761.
class _DiffFailure(Exception):
    """Raised when `git diff` cannot resolve the requested ref range.

    The previous behaviour was to return an empty list, which made the
    pollution gate silently bypass itself whenever `--base origin/main`
    was missing (fresh clones, detached worktrees). The hard-block
    contract is meaningless if the gate can return success without
    inspecting any file. Raise + fail explicitly instead.
    """


def _git_diff_files(rev_range: str | None, mode: str) -> list[str]:
    if mode == "stage":
        cmd = ["git", "diff", "--cached", "--name-only"]
    elif mode == "push":
        if not rev_range:
            raise _DiffFailure("push mode requires a non-empty rev range")
        cmd = ["git", "diff", "--name-only", rev_range]
    else:
        return []
    out = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if out.returncode != 0:
        raise _DiffFailure(
            f"`git {' '.join(cmd[1:])}` exited {out.returncode}: "
            f"{(out.stderr or '').strip()[:200]}"
        )
    return [line.strip() for line in out.stdout.splitlines() if line.strip()]


def _read_blob(rev: str | None, path: str) -> str:
    """Read file content. For staged mode, read from the index. For push mode,
    read from HEAD. For files mode, read from the working tree."""
    if rev:
        out = subprocess.run(
            ["git", "show", f"{rev}:{path}"],
            capture_output=True, text=True, check=False,
        )
        if out.returncode == 0:
            return out.stdout
        return ""
    p = Path(path)
    if p.is_file():
        try:
            return p.read_text(errors="replace")
        except OSError:
            return ""
    return ""


def check_root_allowlist(rev: str) -> list[str]:
    """Companion-track U-1 — return error messages for any top-level path
    on `rev` that is not in ALLOWED_ROOT_PATHS.

    Threat model: a new directory or file appears at the repo root
    unexpectedly. The most likely cause is (a) a test fixture that
    leaked out of /tmp, (b) a stray screenshot or coverage profile not
    covered by .gitignore, or (c) a module that should live under a
    subdirectory but was mis-placed. PR review catches some of this;
    this check catches the rest.

    Adding a legitimate root path requires a same-PR allowlist update.
    The allowlist is short and stable — Pulp's top-level shape rarely
    changes — so the maintenance burden is minimal.
    """
    out = subprocess.run(
        ["git", "ls-tree", "--name-only", rev],
        capture_output=True, text=True, check=False,
    )
    if out.returncode != 0:
        # Treat git failure as hard-block (same posture as _git_diff_files
        # under Codex P1 finding on #1761 — never let the gate silently
        # pass when the underlying git invocation fails).
        return [
            f"git ls-tree {rev} exited {out.returncode}: "
            f"{(out.stderr or '').strip()[:200]}"
        ]
    errors: list[str] = []
    for entry in out.stdout.splitlines():
        name = entry.strip()
        if not name:
            continue
        if name in ALLOWED_ROOT_PATHS:
            continue
        errors.append(
            f"  {name}: unexpected top-level path. If this is "
            "legitimate, add it to ALLOWED_ROOT_PATHS in "
            "tools/scripts/source_tree_pollution_check.py in the "
            "same PR. Otherwise, this is almost certainly a stray "
            "fixture, screenshot, or mis-placed module — move it "
            "under the correct subdirectory or delete it."
        )
    return errors


def check(files: list[str], rev: str | None) -> tuple[list[str], list[str]]:
    """Return (errors, warnings)."""
    errors: list[str] = []
    warnings: list[str] = []
    for path in files:
        # Block #1 — pulp.toml at repo root is always wrong.
        if path == "pulp.toml":
            errors.append(
                f"  {path}: pulp.toml must never be in the source tree. "
                "It's a per-developer/per-project SDK pin generated by "
                "`pulp project init` and should be in .gitignore. The most "
                "likely cause is a CLI test (test_cli_shellout.cpp) that "
                "left a /tmp Clock fixture in the working dir, or a manual "
                "`pulp project bump` ran in the source tree. Delete the "
                "file (`git rm pulp.toml`) and re-stage."
            )
            continue
        # Block #2 — CMakeLists.txt at repo root must declare project(Pulp.
        # Two-pronged check: explicit Clock-fixture signature catches the
        # known #1755 case with a precise error message; positive
        # `project(Pulp` assertion catches ANY future fixture / unrelated
        # CMakeLists.txt being committed at the root (the parallel agent's
        # broader proposal — e.g. somebody pastes an `examples/foo`
        # CMakeLists.txt at the root accidentally).
        if path == "CMakeLists.txt":
            content = _read_blob(rev, path)
            if CLOCK_FIXTURE_SIGNATURE in content:
                errors.append(
                    f"  {path}: contains `project(Clock VERSION 1.0.0` — "
                    "this is the exact signature of the temp CLI test "
                    "fixture from test_cli_shellout.cpp:1605-1624. The "
                    "real Pulp CMakeLists.txt is ~977 lines and starts "
                    "with `project(Pulp VERSION ...`. Restore it from "
                    "main: `git show origin/main:CMakeLists.txt > CMakeLists.txt`. "
                    "PR #1755 accidentally shipped this corruption; #1757 "
                    "was the hotfix; this guard prevents a repeat."
                )
                continue
            # Positive assertion — first ~10 lines must contain
            # `project(Pulp` (case-insensitive, whitespace before `(` ok
            # per Codex P2 followup on #1763). Catches any non-Pulp
            # CMakeLists.txt at the root regardless of the specific
            # fixture, including future examples/foo/CMakeLists.txt
            # accidents.
            head = "\n".join(content.splitlines()[:10])
            if content.strip() and not PULP_PROJECT_PATTERN.search(head):
                errors.append(
                    f"  {path}: first 10 lines do not contain a "
                    "`project(Pulp ...)` declaration (case-insensitive, "
                    "whitespace before `(` allowed). The root "
                    "CMakeLists.txt must declare `project(Pulp ...)` — "
                    "anything else is almost certainly an example or "
                    "fixture file pasted into the wrong place. If you "
                    "genuinely intended to rename the project, update "
                    "both this guard and tools/scripts/test_source_tree_pollution_check.py."
                )
                continue
        # Warn — paths that look like test-fixture leakage.
        for hint in TEMP_FIXTURE_PATH_HINTS:
            if hint in path:
                warnings.append(
                    f"  {path}: path contains `{hint}` which suggests CLI "
                    "test-fixture leakage. Confirm this file actually "
                    "belongs in the repo (it is rare for source files to "
                    "have temp-dir paths in them)."
                )
    return errors, warnings


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--mode", choices=("stage", "push", "files",
                                            "root-allowlist"),
                        default="stage")
    parser.add_argument("--base", default="origin/main",
                        help="for --mode=push, base ref (default origin/main)")
    parser.add_argument("--rev", default="HEAD",
                        help="for --mode=root-allowlist, ref to inspect "
                             "(default HEAD)")
    parser.add_argument("files", nargs="*",
                        help="for --mode=files, explicit file list")
    args = parser.parse_args(argv)

    # Companion-track U-1 — top-level allowlist mode.
    if args.mode == "root-allowlist":
        root_errors = check_root_allowlist(args.rev)
        if root_errors:
            sys.stderr.write("[source-tree-pollution] BLOCKED (root-allowlist):\n")
            for e in root_errors:
                sys.stderr.write(e + "\n")
            return 1
        return 0

    try:
        if args.mode == "stage":
            files = _git_diff_files(None, "stage")
            rev = None
        elif args.mode == "push":
            files = _git_diff_files(f"{args.base}...HEAD", "push")
            rev = "HEAD"
        elif args.mode == "files":
            files = args.files
            rev = None
        else:
            sys.stderr.write(f"unknown mode: {args.mode}\n")
            return 2
    except _DiffFailure as e:
        # Codex P1 finding on #1761 — fail closed when git diff cannot
        # resolve. The previous behaviour silently bypassed the gate
        # whenever `--base origin/main` was missing (fresh clones,
        # detached worktrees), defeating the hard-block contract.
        sys.stderr.write(
            "[source-tree-pollution] BLOCKED: git diff could not resolve "
            "the requested ref range. Pass `--base <ref>` or fix the "
            "git remote so the diff target exists, then retry.\n"
            f"  reason: {e}\n"
        )
        return 1

    errors, warnings = check(files, rev)

    if warnings:
        sys.stderr.write("[source-tree-pollution] warnings:\n")
        for w in warnings:
            sys.stderr.write(w + "\n")

    if errors:
        sys.stderr.write("[source-tree-pollution] BLOCKED:\n")
        for e in errors:
            sys.stderr.write(e + "\n")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
