import json
import os
import subprocess
import sys
import tempfile
import textwrap
import unittest
from pathlib import Path


SCRIPT = Path(__file__).resolve().parent / "cmajor_external.py"


class CmajorExternalScriptTests(unittest.TestCase):
    def make_patch(self, root: Path) -> Path:
        source = root / "CmajorGain.cmajor"
        source.write_text(
            "graph CmajorGain [[ main ]] { input gain.level; input stream float<2> in; output stream float<2> out; }\n",
            encoding="utf-8",
        )

        patch = root / "CmajorGain.cmajorpatch"
        patch.write_text(
            json.dumps(
                {
                    "CmajorVersion": 1,
                    "ID": "dev.generouscorp.pulp.tests.cmajor-gain",
                    "version": "1.0",
                    "name": "Test Cmajor Gain",
                    "manufacturer": "Pulp",
                    "isInstrument": False,
                    "source": source.name,
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        return patch

    def make_fake_cmaj(self, root: Path) -> tuple[Path, Path]:
        log = root / "fake-cmaj-log.txt"
        fake = root / "fake-cmaj"
        fake.write_text(
            textwrap.dedent(
                f"""\
                #!/usr/bin/env python3
                import pathlib
                import sys

                log = pathlib.Path({str(log)!r})
                log.write_text("\\n".join(sys.argv[1:]), encoding="utf-8")

                output = None
                for arg in sys.argv[1:]:
                    if arg.startswith("--output="):
                        output = arg.split("=", 1)[1]
                        break

                if output is None:
                    raise SystemExit(9)

                output_path = pathlib.Path(output)
                if output_path.suffix:
                    output_path.parent.mkdir(parents=True, exist_ok=True)
                    output_path.write_text("// generated by fake cmaj\\n", encoding="utf-8")
                else:
                    output_path.mkdir(parents=True, exist_ok=True)
                    (output_path / "generated.txt").write_text("ok\\n", encoding="utf-8")
                """
            ),
            encoding="utf-8",
        )
        fake.chmod(0o755)
        return fake, log

    def run_script(self, *args: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(SCRIPT), *args],
            check=False,
            capture_output=True,
            text=True,
        )

    def test_doctor_reports_missing_tool_without_failing_by_default(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            patch = self.make_patch(Path(tmp))
            result = self.run_script("doctor", "--patch", str(patch))

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("cmaj: missing", result.stdout)
        self.assertIn("policy: Pulp supports Cmajor through an external toolchain only.", result.stdout)

    def test_doctor_can_require_tool(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            patch = self.make_patch(Path(tmp))
            missing = Path(tmp) / "missing-cmaj"
            result = self.run_script(
                "doctor",
                "--patch",
                str(patch),
                "--cmaj",
                str(missing),
                "--require-tool",
            )

        self.assertEqual(result.returncode, 2)
        self.assertIn("cmaj binary not found", result.stderr)

    def test_generate_uses_fake_cmaj_and_forwards_args(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            patch = self.make_patch(root)
            fake_cmaj, log = self.make_fake_cmaj(root)
            output = root / "out" / "GeneratedProgram.cpp"

            result = self.run_script(
                "generate",
                "--patch",
                str(patch),
                "--output",
                str(output),
                "--target",
                "cpp",
                "--cmaj",
                str(fake_cmaj),
                "--arg=--foo=bar",
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertTrue(output.is_file())
            log_lines = log.read_text(encoding="utf-8").splitlines()
            self.assertEqual(log_lines[0], "generate")
            self.assertIn("--target=cpp", log_lines)
            self.assertIn(f"--output={output}", log_lines)
            self.assertIn("--foo=bar", log_lines)
            self.assertEqual(Path(log_lines[-1]).resolve(), patch.resolve())

    def test_generate_dry_run_can_show_command_without_installed_tool(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            patch = self.make_patch(Path(tmp))
            output = Path(tmp) / "Generated.cpp"
            result = self.run_script(
                "generate",
                "--patch",
                str(patch),
                "--output",
                str(output),
                "--target",
                "cpp",
                "--dry-run",
            )

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("command: cmaj generate --target=cpp", result.stdout)


if __name__ == "__main__":
    unittest.main()
