#!/usr/bin/env python3
"""Unit tests for tools/docs_generate.py."""

from __future__ import annotations

import contextlib
import importlib.util
import io
import pathlib
import subprocess
import sys
import tempfile
import unittest
from unittest import mock


SCRIPT = pathlib.Path(__file__).resolve().parents[1] / "docs_generate.py"
spec = importlib.util.spec_from_file_location("docs_generate", SCRIPT)
assert spec and spec.loader
dg = importlib.util.module_from_spec(spec)
sys.modules["docs_generate"] = dg
spec.loader.exec_module(dg)


class RenderLimitationsTests(unittest.TestCase):
    def test_missing_generator_returns_notice(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            missing = pathlib.Path(td) / "missing.py"
            with mock.patch.object(dg, "LIST_LIMITATIONS", missing):
                self.assertEqual(
                    dg.render_limitations(),
                    "_(limitations generator missing)_\n",
                )

    def test_generator_exception_is_reported(self) -> None:
        with mock.patch.object(dg, "LIST_LIMITATIONS", SCRIPT), \
             mock.patch.object(
                 dg.subprocess,
                 "run",
                 side_effect=OSError("no python"),
             ):
            self.assertEqual(
                dg.render_limitations(),
                "_(limitations generator failed: no python)_\n",
            )

    def test_nonzero_generator_exit_surfaces_stderr(self) -> None:
        result = subprocess.CompletedProcess(
            args=["python3"],
            returncode=7,
            stdout="",
            stderr="bad matrix\n",
        )
        with mock.patch.object(dg, "LIST_LIMITATIONS", SCRIPT), \
             mock.patch.object(dg.subprocess, "run", return_value=result):
            rendered = dg.render_limitations()

        self.assertIn("_(limitations generator exited 7)_", rendered)
        self.assertIn("bad matrix", rendered)

    def test_success_strips_nested_generated_comment(self) -> None:
        result = subprocess.CompletedProcess(
            args=["python3"],
            returncode=0,
            stdout="<!-- generated by tools/list_limitations.py -->\n| A | B |\n",
            stderr="",
        )
        with mock.patch.object(dg, "LIST_LIMITATIONS", SCRIPT), \
             mock.patch.object(dg.subprocess, "run", return_value=result):
            self.assertEqual(dg.render_limitations(), "| A | B |\n")

    def test_empty_success_reports_no_limitations(self) -> None:
        result = subprocess.CompletedProcess(
            args=["python3"],
            returncode=0,
            stdout="<!-- generated by tools/list_limitations.py -->\n\n",
            stderr="",
        )
        with mock.patch.object(dg, "LIST_LIMITATIONS", SCRIPT), \
             mock.patch.object(dg.subprocess, "run", return_value=result):
            self.assertEqual(
                dg.render_limitations(),
                "_(no limitations declared in support-matrix.yaml)_\n",
            )


class RewriteTests(unittest.TestCase):
    def test_rewrite_replaces_known_region(self) -> None:
        text = (
            "before\n"
            "<!-- generated:start id=limitations -->\n"
            "stale\n"
            "<!-- generated:end id=limitations -->\n"
            "after\n"
        )
        with mock.patch.dict(dg.GENERATORS, {"limitations": lambda: "fresh\n"}):
            self.assertEqual(
                dg.rewrite(text),
                (
                    "before\n"
                    "<!-- generated:start id=limitations -->\n"
                    "fresh\n"
                    "<!-- generated:end id=limitations -->\n"
                    "after\n"
                ),
            )

    def test_rewrite_reports_unknown_generator(self) -> None:
        text = (
            "<!-- generated:start id=missing -->\n"
            "stale\n"
            "<!-- generated:end id=missing -->\n"
        )
        self.assertEqual(
            dg.rewrite(text),
            (
                "<!-- generated:start id=missing -->\n"
                "_(unknown generator id='missing')_\n"
                "<!-- generated:end id=missing -->\n"
            ),
        )

    def test_rewrite_adds_missing_end_marker(self) -> None:
        with mock.patch.dict(dg.GENERATORS, {"limitations": lambda: "fresh\n"}):
            self.assertEqual(
                dg.rewrite("x\n<!-- generated:start id=limitations -->\nstale\n"),
                "x\n<!-- generated:start id=limitations -->\nfresh\n"
                "<!-- generated:end id=limitations -->\n",
            )


class MainTests(unittest.TestCase):
    def _run_main(self, argv: list[str], path: pathlib.Path) -> tuple[int, str, str]:
        stdout = io.StringIO()
        stderr = io.StringIO()
        with mock.patch.object(dg, "CAPABILITIES_PATH", path), \
             mock.patch.object(sys, "argv", ["docs_generate.py", *argv]), \
             contextlib.redirect_stdout(stdout), \
             contextlib.redirect_stderr(stderr):
            rc = dg.main()
        return rc, stdout.getvalue(), stderr.getvalue()

    def test_check_mode_passes_when_current_matches_rewrite(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            path = pathlib.Path(td) / "capabilities.md"
            path.write_text("plain\n", encoding="utf-8")

            rc, stdout, stderr = self._run_main(["check"], path)

        self.assertEqual(rc, 0)
        self.assertEqual(stdout, "docs-generate: OK\n")
        self.assertEqual(stderr, "")

    def test_check_mode_reports_drift_with_short_diff(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            path = pathlib.Path(td) / "capabilities.md"
            path.write_text(
                "<!-- generated:start id=limitations -->\nstale\n"
                "<!-- generated:end id=limitations -->\n",
                encoding="utf-8",
            )
            with mock.patch.dict(dg.GENERATORS, {"limitations": lambda: "fresh\n"}):
                rc, stdout, stderr = self._run_main(["check"], path)

        self.assertEqual(rc, 1)
        self.assertEqual(stderr, "")
        self.assertIn("docs-generate: DRIFT DETECTED", stdout)
        self.assertIn("-stale", stdout)
        self.assertIn("+fresh", stdout)

    def test_generate_mode_rewrites_file(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            path = pathlib.Path(td) / "capabilities.md"
            path.write_text(
                "<!-- generated:start id=limitations -->\nstale\n"
                "<!-- generated:end id=limitations -->\n",
                encoding="utf-8",
            )
            with mock.patch.dict(dg.GENERATORS, {"limitations": lambda: "fresh\n"}):
                rc, stdout, stderr = self._run_main([], path)

            self.assertEqual(rc, 0)
            self.assertEqual(stderr, "")
            self.assertIn("rewrote", stdout)
            self.assertIn("fresh", path.read_text(encoding="utf-8"))

    def test_generate_mode_reports_no_changes(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            path = pathlib.Path(td) / "capabilities.md"
            path.write_text("plain\n", encoding="utf-8")

            rc, stdout, stderr = self._run_main(["generate"], path)

        self.assertEqual(rc, 0)
        self.assertEqual(stdout, "docs-generate: no changes\n")
        self.assertEqual(stderr, "")

    def test_read_failure_returns_input_error(self) -> None:
        missing = pathlib.Path("/definitely/missing/capabilities.md")
        rc, stdout, stderr = self._run_main(["check"], missing)

        self.assertEqual(rc, 2)
        self.assertEqual(stdout, "")
        self.assertIn("Failed to read", stderr)


if __name__ == "__main__":
    unittest.main()
