#!/usr/bin/env python3
"""Coverage-lane tests for tools/cmake/scripts/encode_binary_data.py."""

from __future__ import annotations

import contextlib
import importlib.util
import io
import pathlib
import subprocess
import sys
import tempfile
import unittest


SCRIPT = (
    pathlib.Path(__file__).resolve().parents[1]
    / "cmake"
    / "scripts"
    / "encode_binary_data.py"
)
spec = importlib.util.spec_from_file_location("encode_binary_data", SCRIPT)
assert spec and spec.loader
encoder = importlib.util.module_from_spec(spec)
sys.modules["encode_binary_data"] = encoder
spec.loader.exec_module(encoder)


class EmitTests(unittest.TestCase):
    def test_emit_writes_cpp_with_hex_rows_and_external_symbols(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = pathlib.Path(td)
            src = root / "asset.bin"
            out = root / "generated" / "asset.cpp"
            src.write_bytes(bytes(range(18)))

            encoder._emit(src, "pulp::assets", "asset_blob", out)

            text = out.read_text(encoding="utf-8")

        self.assertIn(
            "Auto-generated by tools/cmake/scripts/encode_binary_data.py", text
        )
        self.assertIn("// Source: asset.bin", text)
        self.assertIn("#include <cstddef>", text)
        self.assertIn("namespace pulp::assets {", text)
        self.assertIn("extern const unsigned char asset_blob[] = {", text)
        self.assertIn(
            "    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, "
            "0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,",
            text,
        )
        self.assertIn("    0x10, 0x11,", text)
        self.assertIn("extern const std::size_t asset_blob_size = 18;", text)
        self.assertIn("}  // namespace pulp::assets", text)

    def test_emit_handles_empty_input(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = pathlib.Path(td)
            src = root / "empty.bin"
            out = root / "empty.cpp"
            src.write_bytes(b"")

            encoder._emit(src, "empty_ns", "empty_blob", out)

            text = out.read_text(encoding="utf-8")

        self.assertIn("extern const unsigned char empty_blob[] = {\n};", text)
        self.assertIn("extern const std::size_t empty_blob_size = 0;", text)


class MainTests(unittest.TestCase):
    def test_main_writes_output_and_creates_parent_dirs(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = pathlib.Path(td)
            src = root / "asset.bin"
            out = root / "nested" / "asset.cpp"
            src.write_bytes(b"Pulp")

            rc = encoder.main(
                [
                    "--src",
                    str(src),
                    "--out",
                    str(out),
                    "--namespace",
                    "ns",
                    "--var",
                    "payload",
                ]
            )

            self.assertEqual(rc, 0)
            self.assertTrue(out.exists())
            self.assertIn("0x50, 0x75, 0x6c, 0x70,", out.read_text(encoding="utf-8"))

    def test_main_reports_missing_input(self) -> None:
        stderr = io.StringIO()
        with tempfile.TemporaryDirectory() as td:
            root = pathlib.Path(td)
            missing = root / "missing.bin"
            out = root / "out.cpp"

            with contextlib.redirect_stderr(stderr):
                rc = encoder.main(
                    [
                        "--src",
                        str(missing),
                        "--out",
                        str(out),
                        "--namespace",
                        "ns",
                        "--var",
                        "payload",
                    ]
                )

        self.assertEqual(rc, 1)
        self.assertIn("encode_binary_data.py: input not found", stderr.getvalue())

    def test_main_missing_required_argument_exits_from_argparse(self) -> None:
        stderr = io.StringIO()
        with self.assertRaises(SystemExit) as raised, contextlib.redirect_stderr(stderr):
            encoder.main(["--src", "asset.bin"])

        self.assertEqual(raised.exception.code, 2)
        self.assertIn("usage:", stderr.getvalue())

    def test_script_entrypoint_invokes_main(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = pathlib.Path(td)
            src = root / "asset.bin"
            out = root / "asset.cpp"
            src.write_bytes(b"cli")

            proc = subprocess.run(
                [
                    sys.executable,
                    str(SCRIPT),
                    "--src",
                    str(src),
                    "--out",
                    str(out),
                    "--namespace",
                    "ns",
                    "--var",
                    "payload",
                ],
                check=False,
                capture_output=True,
                text=True,
            )

            self.assertEqual(proc.returncode, 0, proc.stderr)
            self.assertIn("0x63, 0x6c, 0x69,", out.read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
