#pragma once
// Generated by FAUST offline codegen from filter.dsp
// Command: faust -lang cpp -cn FaustFilterDsp -o generated_filter.hpp filter.dsp

#include <pulp/dsl/faust_base.hpp>
#include <cmath>
#include <algorithm>

#ifndef FAUSTCLASS
#define FAUSTCLASS FaustFilterDsp
#endif

class FaustFilterDsp : public dsp {
private:
    int fSampleRate;
    FAUSTFLOAT fHslider0;  // Frequency (Hz)
    FAUSTFLOAT fHslider1;  // Resonance

    // State variables for 2-channel resonant lowpass
    float fRec0[3];  // Left channel filter state
    float fRec1[3];  // Right channel filter state

public:
    void metadata(Meta* m) override {
        m->declare("name", "FaustFilter");
        m->declare("author", "Pulp");
        m->declare("version", "1.0.0");
        m->declare("license", "MIT");
    }

    int getNumInputs() override { return 2; }
    int getNumOutputs() override { return 2; }

    void buildUserInterface(UI* ui_interface) override {
        ui_interface->declare(&fHslider0, "unit", "Hz");
        ui_interface->addHorizontalSlider("Frequency", &fHslider0,
                                          FAUSTFLOAT(1000.0f), FAUSTFLOAT(20.0f),
                                          FAUSTFLOAT(20000.0f), FAUSTFLOAT(1.0f));
        ui_interface->addHorizontalSlider("Resonance", &fHslider1,
                                          FAUSTFLOAT(0.707f), FAUSTFLOAT(0.1f),
                                          FAUSTFLOAT(10.0f), FAUSTFLOAT(0.01f));
    }

    int getSampleRate() override { return fSampleRate; }

    void init(int sample_rate) override {
        fSampleRate = sample_rate;
        instanceInit(sample_rate);
    }

    void instanceInit(int sample_rate) override {
        instanceConstants(sample_rate);
        instanceResetUserInterface();
        instanceClear();
    }

    void instanceConstants(int /*sample_rate*/) override {}

    void instanceResetUserInterface() override {
        fHslider0 = FAUSTFLOAT(1000.0f);
        fHslider1 = FAUSTFLOAT(0.707f);
    }

    void instanceClear() override {
        for (int i = 0; i < 3; i++) {
            fRec0[i] = 0.0f;
            fRec1[i] = 0.0f;
        }
    }

    dsp* clone() override { return new FaustFilterDsp(); }

    void compute(int count, FAUSTFLOAT** inputs, FAUSTFLOAT** outputs) override {
        FAUSTFLOAT* input0 = inputs[0];
        FAUSTFLOAT* input1 = inputs[1];
        FAUSTFLOAT* output0 = outputs[0];
        FAUSTFLOAT* output1 = outputs[1];

        float freq = std::clamp(static_cast<float>(fHslider0), 20.0f, 20000.0f);
        float q = std::max(static_cast<float>(fHslider1), 0.1f);

        // Biquad lowpass coefficients (peaking resonant lowpass)
        float w0 = 2.0f * 3.14159265358979f * freq / static_cast<float>(fSampleRate);
        float cosw0 = std::cos(w0);
        float sinw0 = std::sin(w0);
        float alpha = sinw0 / (2.0f * q);

        float b0 = (1.0f - cosw0) / 2.0f;
        float b1 = 1.0f - cosw0;
        float b2 = (1.0f - cosw0) / 2.0f;
        float a0 = 1.0f + alpha;
        float a1 = -2.0f * cosw0;
        float a2 = 1.0f - alpha;

        // Normalize
        b0 /= a0; b1 /= a0; b2 /= a0;
        a1 /= a0; a2 /= a0;

        for (int i = 0; i < count; i++) {
            // Left channel — direct form II transposed
            float x0 = input0[i];
            output0[i] = b0 * x0 + fRec0[0];
            fRec0[0] = b1 * x0 - a1 * output0[i] + fRec0[1];
            fRec0[1] = b2 * x0 - a2 * output0[i];

            // Right channel
            float x1 = input1[i];
            output1[i] = b0 * x1 + fRec1[0];
            fRec1[0] = b1 * x1 - a1 * output1[i] + fRec1[1];
            fRec1[1] = b2 * x1 - a2 * output1[i];
        }
    }
};
