#pragma once
// Generated by FAUST offline codegen from tremolo.dsp
// Command: faust -lang cpp -cn FaustTremoloDsp -o generated_tremolo.hpp tremolo.dsp

#include <pulp/dsl/faust_base.hpp>
#include <cmath>
#include <algorithm>

#ifndef FAUSTCLASS
#define FAUSTCLASS FaustTremoloDsp
#endif

class FaustTremoloDsp : public dsp {
private:
    int fSampleRate;
    FAUSTFLOAT fHslider0;  // Rate (Hz)
    FAUSTFLOAT fHslider1;  // Depth

    // Oscillator state
    float fPhase;

public:
    void metadata(Meta* m) override {
        m->declare("name", "FaustTremolo");
        m->declare("author", "Pulp");
        m->declare("version", "1.0.0");
        m->declare("license", "MIT");
    }

    int getNumInputs() override { return 2; }
    int getNumOutputs() override { return 2; }

    void buildUserInterface(UI* ui_interface) override {
        ui_interface->declare(&fHslider0, "unit", "Hz");
        ui_interface->addHorizontalSlider("Rate", &fHslider0,
                                          FAUSTFLOAT(4.0f), FAUSTFLOAT(0.1f),
                                          FAUSTFLOAT(20.0f), FAUSTFLOAT(0.01f));
        ui_interface->addHorizontalSlider("Depth", &fHslider1,
                                          FAUSTFLOAT(0.5f), FAUSTFLOAT(0.0f),
                                          FAUSTFLOAT(1.0f), FAUSTFLOAT(0.01f));
    }

    int getSampleRate() override { return fSampleRate; }

    void init(int sample_rate) override {
        fSampleRate = sample_rate;
        instanceInit(sample_rate);
    }

    void instanceInit(int sample_rate) override {
        instanceConstants(sample_rate);
        instanceResetUserInterface();
        instanceClear();
    }

    void instanceConstants(int /*sample_rate*/) override {}

    void instanceResetUserInterface() override {
        fHslider0 = FAUSTFLOAT(4.0f);
        fHslider1 = FAUSTFLOAT(0.5f);
    }

    void instanceClear() override {
        fPhase = 0.0f;
    }

    dsp* clone() override { return new FaustTremoloDsp(); }

    void compute(int count, FAUSTFLOAT** inputs, FAUSTFLOAT** outputs) override {
        FAUSTFLOAT* input0 = inputs[0];
        FAUSTFLOAT* input1 = inputs[1];
        FAUSTFLOAT* output0 = outputs[0];
        FAUSTFLOAT* output1 = outputs[1];

        float rate = static_cast<float>(fHslider0);
        float depth = static_cast<float>(fHslider1);
        float phase_inc = rate / static_cast<float>(fSampleRate);

        for (int i = 0; i < count; i++) {
            // tremolo = 1 - depth * (0.5 + 0.5 * sin(2*pi*phase))
            float osc = std::sin(2.0f * 3.14159265358979f * fPhase);
            float mod = 1.0f - depth * (0.5f + 0.5f * osc);

            output0[i] = input0[i] * mod;
            output1[i] = input1[i] * mod;

            fPhase += phase_inc;
            if (fPhase >= 1.0f) fPhase -= 1.0f;
        }
    }
};
