// bundled_fonts.cpp — see bundled_fonts.hpp.
//
// At build time `pulp_add_binary_data(pulp-bundled-fonts SOURCES …)` produces
// `pulp-bundled-fonts_data.hpp`, which declares one `extern const unsigned
// char <name>[]` + `<name>_size` per embedded asset. We mirror that list here
// so we can iterate over every bundled .ttf without scraping CMake state at
// runtime.
//
// If `PULP_HAS_SKIA` is not defined we still ship a translation unit so the
// header has *something* to link against in non-GPU builds; the entry points
// are gated on the same macro.

#include <pulp/canvas/bundled_fonts.hpp>
#include <pulp/canvas/font_resolver.hpp>
#include <pulp/canvas/font_options.hpp>

#ifdef PULP_HAS_SKIA

#include <array>
#include <atomic>
#include <fstream>
#include <mutex>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#include "include/core/SkData.h"
#include "include/core/SkFontMgr.h"
#include "include/core/SkString.h"
#include "include/core/SkTypeface.h"

// Platform font manager — paths mirror core/canvas/src/skia_canvas.cpp.
// Needed by the public `register_font` API so plugin authors can register
// their own .ttf/.otf files without the rest of `pulp::canvas` having to
// inject a font manager. Keep this matrix in sync with the `get_font_manager()`
// switch in skia_canvas.cpp.
#if defined(__APPLE__)
#include "include/ports/SkFontMgr_mac_ct.h"
#elif defined(_WIN32)
#include "include/ports/SkTypeface_win.h"
#elif defined(__ANDROID__)
#include "include/ports/SkFontMgr_android.h"
#include "include/ports/SkFontScanner_FreeType.h"
#elif defined(__linux__)
#include "include/ports/SkFontMgr_fontconfig.h"
#include "include/ports/SkFontScanner_FreeType.h"
#endif

#include "pulp-bundled-fonts_data.hpp" // Generated by pulp_add_binary_data.

namespace pulp::canvas {

namespace {

struct BundledBlob {
    const char* asset_name;       // Original file name (for diagnostics).
    const unsigned char* data;
    std::size_t size;
};

// One entry per .ttf listed in core/canvas/CMakeLists.txt. Keep this list and
// the CMake SOURCES list in sync — there is intentionally no auto-discovery,
// so failures show up as a "file not declared" link error rather than a
// silent runtime miss.
const std::array<BundledBlob, 2>& bundled_blobs() {
    static const std::array<BundledBlob, 2> kBlobs = {{
        {"Inter-Regular.ttf",
         pulp_bundled_fonts::Inter_Regular_ttf,
         pulp_bundled_fonts::Inter_Regular_ttf_size},
        {"JetBrainsMono-Regular.ttf",
         pulp_bundled_fonts::JetBrainsMono_Regular_ttf,
         pulp_bundled_fonts::JetBrainsMono_Regular_ttf_size},
    }};
    return kBlobs;
}

// First call with a non-null `mgr` lazily materialises every blob into an
// SkTypeface keyed by the face's reported family name (NOT the file name —
// we trust Skia's name table parse over our naming convention). Lookup is
// O(1) average.
//
// The `mgr` argument is forwarded only on the initialising call; subsequent
// callers reuse the cache regardless of which font manager they hand in.
// We deliberately do NOT call `std::call_once` here: if the very first
// caller passes a null manager (e.g. a unit test that is verifying graceful
// degradation), `call_once` would burn the once-flag and the *next* caller
// with a real mgr would see an empty cache forever. Use a guard flag that
// only flips on success.
const std::unordered_map<std::string, sk_sp<SkTypeface>>&
ensure_registered(SkFontMgr* mgr) {
    static std::mutex lock;
    static bool initialized = false;
    static std::unordered_map<std::string, sk_sp<SkTypeface>> by_family;

    std::lock_guard<std::mutex> guard(lock);
    if (initialized || !mgr) return by_family;

    for (const auto& blob : bundled_blobs()) {
        if (!blob.data || blob.size == 0) continue;
        // SkData::MakeWithoutCopy is safe here: the array data has static
        // storage duration (lives for the entire process) and the
        // SkTypeface only holds a reference for as long as it's in our
        // cache, which is also static.
        auto sk_data = SkData::MakeWithoutCopy(blob.data, blob.size);
        sk_sp<SkTypeface> face = mgr->makeFromData(std::move(sk_data));
        if (!face) continue;

        SkString family;
        face->getFamilyName(&family);
        if (family.isEmpty()) continue;

        // First face wins for a given family. The bundle currently has at
        // most one face per family, so collisions just mean we shipped a
        // duplicate — keep the first deterministically.
        by_family.emplace(std::string(family.c_str()), std::move(face));
    }

    initialized = true;
    return by_family;
}

} // namespace

sk_sp<SkTypeface> match_bundled_typeface(SkFontMgr* mgr,
                                         const std::string& family,
                                         SkFontStyle style) {
    const auto& cache = ensure_registered(mgr);
    auto it = cache.find(family);
    if (it == cache.end()) return nullptr;

    // The bundle currently ships only Regular/Upright faces. If the caller
    // wants something else (bold, italic, …) we MUST return nullptr so the
    // skia_canvas typeface lookup keeps walking and lets
    // SkFontMgr::matchFamilyStyle pick a system-installed bold/italic
    // variant — otherwise #932 silently regresses #927's weight/slant
    // honouring (Codex P2 on PR #956).
    SkFontStyle have = it->second->fontStyle();
    if (have.weight() != style.weight() || have.slant() != style.slant()) {
        return nullptr;
    }
    return it->second;
}

std::size_t bundled_font_count() {
    return bundled_blobs().size();
}

// ── Plugin-registered font registry (pulp #1150) ─────────────────────────────
// Bundled fonts are baked in at build time and live forever in the binary;
// plugin-registered fonts come at runtime from `register_font(...)`. They
// share lookup mechanics (cache by family name, style-aware miss to keep
// weight/slant honouring intact) but live in a separate map so the bundled
// list stays canonical and we never accidentally drop a baked-in face when
// a plugin registers an overlapping family.

namespace {

// pulp #2163 — register_font is called per-typeface, often N times for
// the same family (one per weight/slant variant) when a developer drops
// a folder full of TTFs. Before #2163 this map kept exactly one face
// per family name, so a later "IBM Plex Mono" registration silently
// overwrote a previous one — the Italic could end up keyed under the
// family while a Regular request landed on the Italic and was
// rejected by match_registered_typeface's style filter, returning
// nullptr. Now we keep every registered face per family and let
// match_registered_typeface pick the best style match (exact first,
// then closest).
struct RegisteredEntry {
    std::vector<sk_sp<SkTypeface>> faces;
};

std::mutex& registered_mutex() {
    static std::mutex m;
    return m;
}

std::unordered_map<std::string, RegisteredEntry>& registered_fonts() {
    static std::unordered_map<std::string, RegisteredEntry> map;
    return map;
}

// Monotonic counter exposed via `font_registration_generation()`. Every
// successful mutation of process-global font state bumps it so downstream
// typeface caches (skia_canvas.cpp, text_shaper.cpp) can invalidate
// themselves on the next lookup. Atomic so callers don't need to hold the
// registration lock when probing.
std::atomic<std::uint64_t>& registration_generation() {
    static std::atomic<std::uint64_t> g{0};
    return g;
}

void bump_generation() noexcept {
    registration_generation().fetch_add(1, std::memory_order_acq_rel);
}

} // namespace

// pulp #2163 / font v2 Slice 1.1.a — single canonical platform-font-manager
// helper, exported from `bundled_fonts.hpp`. Replaces the five inline
// SkFontMgr_New_* switch blocks that previously lived in skia_canvas.cpp,
// text_shaper.cpp, sdf_atlas.cpp, bundled_fonts.cpp (×2), and the seed
// copy in font_resolver.cpp.
sk_sp<SkFontMgr> platform_font_manager() {
    static sk_sp<SkFontMgr> mgr;
    static bool tried = false;
    if (!tried) {
        tried = true;
#if defined(__APPLE__)
        mgr = SkFontMgr_New_CoreText(nullptr);
#elif defined(_WIN32)
        mgr = SkFontMgr_New_DirectWrite();
#elif defined(__ANDROID__)
        mgr = SkFontMgr_New_Android(nullptr, SkFontScanner_Make_FreeType());
#elif defined(__linux__)
        mgr = SkFontMgr_New_FontConfig(nullptr, SkFontScanner_Make_FreeType());
#endif
    }
    return mgr;
}

sk_sp<SkTypeface> match_registered_typeface(const std::string& family,
                                            SkFontStyle style) {
    if (family.empty()) return nullptr;
    std::lock_guard<std::mutex> guard(registered_mutex());
    auto& map = registered_fonts();
    auto it = map.find(family);
    if (it == map.end() || it->second.faces.empty()) return nullptr;

    // pulp #2163 — pass 1: exact match on weight + slant. This is the
    // ideal path: caller asked for Regular/Upright, a Regular/Upright
    // is registered, hand it back unchanged.
    for (const auto& f : it->second.faces) {
        if (!f) continue;
        SkFontStyle have = f->fontStyle();
        if (have.weight() == style.weight() && have.slant() == style.slant()) {
            return f;
        }
    }

    // pulp #2163 — pass 2: best-effort closest match. The pre-#2163
    // contract returned nullptr here so skia_canvas's cascade could
    // walk on to matchFamilyStyle (which synthesizes faux bold). That
    // contract was fine when the registry held one face per family,
    // but with multi-face registration we now have e.g. Light + Bold +
    // SemiBold for the same family and refusing to return any of them
    // for a Regular request would force a system-default fallback that
    // breaks Unicode coverage (the original tofu symptom). Closest-by-
    // weight, prefer-matching-slant heuristic — same rule CSS engines
    // apply in `font-style: italic` selection.
    sk_sp<SkTypeface> best;
    int best_score = std::numeric_limits<int>::min();
    for (const auto& f : it->second.faces) {
        if (!f) continue;
        SkFontStyle have = f->fontStyle();
        int score = -std::abs(have.weight() - style.weight())
                    - (have.slant() == style.slant() ? 0 : 50);
        if (score > best_score) { best_score = score; best = f; }
    }
    return best;
}

bool register_font(const std::uint8_t* data, std::size_t size,
                   const std::string& family_override) {
    if (!data || size == 0) return false;

    SkFontMgr* mgr = platform_font_manager().get();
    if (!mgr) {
        // No platform font manager → no way to materialise an SkTypeface
        // from raw bytes (the prebuilt Skia we ship doesn't link FreeType
        // standalone). Calling code should treat this as a soft failure.
        return false;
    }

    // SkData::MakeWithCopy so the caller can free `data` immediately. The
    // typeface owns the SkData reference for its full lifetime.
    auto sk_data = SkData::MakeWithCopy(data, size);
    sk_sp<SkTypeface> face = mgr->makeFromData(std::move(sk_data));
    if (!face) return false;

    std::string family = family_override;
    if (family.empty()) {
        SkString sk_family;
        face->getFamilyName(&sk_family);
        family.assign(sk_family.c_str());
    }
    if (family.empty()) {
        // Without a usable family name we have no key to register under —
        // refuse rather than insert under "".
        return false;
    }

    {
        std::lock_guard<std::mutex> guard(registered_mutex());
        // pulp #2163 — append rather than overwrite. The lookup side
        // picks the best style match across all registered faces for
        // this family. Idempotency: skip if this exact typeface ptr is
        // already present (same Skia identity), but allow multiple
        // physically-distinct faces (a Regular + Italic + Bold trio is
        // the normal case for "drop the font family folder in").
        auto& entry = registered_fonts()[family];
        bool dup = false;
        for (const auto& existing : entry.faces) {
            if (existing.get() == face.get()) { dup = true; break; }
        }
        if (!dup) entry.faces.push_back(std::move(face));
    }
    bump_generation();
    return true;
}

bool register_font_file(const std::string& path,
                        const std::string& family_override) {
    if (path.empty()) return false;
    std::ifstream file(path, std::ios::binary | std::ios::ate);
    if (!file.is_open()) return false;
    std::streamsize size = file.tellg();
    if (size <= 0) return false;
    file.seekg(0, std::ios::beg);
    std::vector<std::uint8_t> bytes(static_cast<std::size_t>(size));
    if (!file.read(reinterpret_cast<char*>(bytes.data()), size)) return false;
    return register_font(bytes.data(), bytes.size(), family_override);
}

FontProbe probe_font_glyph(const std::string& family,
                           int weight, int slant,
                           std::uint32_t codepoint) {
    FontProbe out;
    out.family = family;
    out.codepoint = codepoint;

    if (family.empty()) return out;

    // pulp #2163 / font v2 Slice 1.1.a — was a hand-rolled cascade that
    // mirrored get_cached_typeface_single. Now routes through
    // FontResolver so the probe sees exactly what fill_text would
    // resolve to. The resolver's cache is keyed on the full
    // FontOptions blob so a probe call doesn't "pollute" — it
    // pre-populates a key a subsequent real call would have hit
    // anyway.
    FontOptions opts;
    opts.family_stack.push_back(family);
    opts.weight = static_cast<float>(weight);
    opts.slant  = slant ? FontSlant::Italic : FontSlant::Normal;
    auto resolved = FontResolver::instance().resolve_family_list(opts);
    if (!resolved.typeface) return out;

    out.family_resolved = true;
    out.resolved_family = resolved.actual_family;
    out.glyph_present = (resolved.typeface->unicharToGlyph(
        static_cast<SkUnichar>(codepoint)) != 0);
    return out;
}

bool is_font_registered(const std::string& family) {
    if (family.empty()) return false;
    std::lock_guard<std::mutex> guard(registered_mutex());
    auto& map = registered_fonts();
    return map.find(family) != map.end();
}

std::uint64_t font_registration_generation() noexcept {
    return registration_generation().load(std::memory_order_acquire);
}

void bump_font_registration_generation() noexcept {
    bump_generation();
}

// pulp #2163 — font v2 Slice 2.8 skeleton. The Phase 2 implementation
// slice replaces this with a Chromium-`ots`-style sanitizer that
// verifies the TTF/OTF table directory + critical-table checksums and
// rejects malformed inputs. For now we just confirm Skia can parse the
// bytes into an SkTypeface — that gates the most catastrophic crashes
// (truncated streams, garbage data) without the full per-table audit.
bool validate_font_bytes(const std::uint8_t* data, std::size_t size) {
    if (!data || size == 0) return false;
    auto sk_data = SkData::MakeWithCopy(data, size);
    if (!sk_data) return false;
    auto mgr = platform_font_manager();
    if (!mgr) return true; // can't validate without a mgr; accept conservatively
    auto face = mgr->makeFromData(std::move(sk_data));
    return static_cast<bool>(face);
}

} // namespace pulp::canvas

#endif // PULP_HAS_SKIA

// Provide the no-Skia stubs so callers can read / bump the generation
// unconditionally. With no Skia the bump is a no-op (there's nothing
// downstream to invalidate) and the read always returns 0.
#ifndef PULP_HAS_SKIA
namespace pulp::canvas {
std::uint64_t font_registration_generation() noexcept { return 0; }
void bump_font_registration_generation() noexcept {}
} // namespace pulp::canvas
#endif
