#!/usr/bin/env bash
# Configure-time smoke for pulp_add_ios_auv3(): runs an iOS Simulator
# CMake configure of the Pulp tree and asserts that the example's AUv3
# target wiring is emitted. Exits 77 (CTest skipped) when the iOS SDK
# is not available on the host.
set -euo pipefail

pulp_root="${1:-}"
if [[ -z "${pulp_root}" ]]; then
    echo "usage: $0 <pulp-source-dir>" >&2
    exit 2
fi

if ! command -v xcrun >/dev/null 2>&1; then
    echo "SKIP: xcrun not available on this host"
    exit 77
fi
if ! xcrun --sdk iphonesimulator --show-sdk-path >/dev/null 2>&1; then
    echo "SKIP: iPhoneSimulator SDK not available on this host"
    exit 77
fi

build_dir="$(mktemp -d -t pulp-ios-auv3-XXXXXX)"
trap 'rm -rf "${build_dir}"' EXIT

log="${build_dir}/configure.log"

set +e
# 1200s configure ceiling (20 min) — fresh worktrees on the self-hosted
# runner spend 4–5 minutes on libc header detection (alloca / float /
# iconv / inttypes / ...), 1–2 minutes on mbedtls FetchContent unpack
# (which writes nothing to the log until it finishes), 1–2 minutes on
# Yoga / SheenBidi / yaml-cpp, plus the Xcode generator's try-compile
# sweep. Observed cold-cache configure on a Mac mini: ~530s; second
# run with FetchContent caches warm: ~75s. 1200s leaves headroom for
# slower hosts. Old 90s / 240s / 600s ceilings all silently flipped
# the test to SKIP on cold runs and masked real failures (the
# 2026-05-27 iPad walkthrough exposed this). The CTest outer TIMEOUT
# is 2700s, so a 1200s configure still leaves 25 minutes for the
# .appex + HostApp build step that follows.
if command -v gtimeout >/dev/null 2>&1; then
    timeout_cmd=(gtimeout 1200s)
elif command -v timeout >/dev/null 2>&1; then
    timeout_cmd=(timeout 1200s)
elif command -v perl >/dev/null 2>&1; then
    timeout_cmd=(perl -e 'alarm shift; exec @ARGV' 1200)
else
    timeout_cmd=()
fi

"${timeout_cmd[@]}" cmake \
    -S "${pulp_root}" \
    -B "${build_dir}/build" \
    -G Xcode \
    -DCMAKE_SYSTEM_NAME=iOS \
    -DCMAKE_OSX_SYSROOT=iphonesimulator \
    -DCMAKE_OSX_ARCHITECTURES=arm64 \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=16.4 \
    -DPULP_ENABLE_GPU=OFF \
    -DPULP_BUILD_TESTS=OFF \
    -DPULP_BUILD_EXAMPLES=ON \
    -DPULP_TEXT_SHAPING=OFF \
    >"${log}" 2>&1
status=$?
set -e

if [[ ${status} -eq 124 || ${status} -eq 142 ]]; then
    echo "SKIP: iOS Simulator configure exceeded 1200s; likely Xcode generator hang"
    tail -n 80 "${log}" >&2
    exit 77
fi

if [[ ${status} -ne 0 ]]; then
    echo "FAIL: iOS Simulator configure failed (status ${status})"
    tail -n 80 "${log}" >&2
    exit 1
fi

if ! grep -q 'Pulp iOS AUv3: PulpSineSynth (type: aumu, subtype: PsSn)' "${log}"; then
    echo "FAIL: expected 'Pulp iOS AUv3: PulpSineSynth (type: aumu, subtype: PsSn)' status message"
    grep -i 'auv3\|pulp_add_ios_auv3' "${log}" >&2 || true
    exit 1
fi

if [[ ! -d "${build_dir}/build/Pulp.xcodeproj" ]]; then
    echo "FAIL: Pulp.xcodeproj not generated"
    exit 1
fi

if ! grep -q 'PulpSineSynth_AUv3' "${build_dir}/build/Pulp.xcodeproj/project.pbxproj"; then
    echo "FAIL: PulpSineSynth_AUv3 target not present in generated Xcode project"
    exit 1
fi

# The HostApp target generated by pulp_add_ios_host_app() must also be
# present in the Xcode project so `cmake --build` can drive the .app
# build that wraps the .appex for Simulator + physical iPad install.
# Configure-only assertion — the actual HostApp build runs behind
# PULP_IOS_AUV3_SMOKE_BUILD=1 below.
if ! grep -q 'PulpSineSynth_HostApp' "${build_dir}/build/Pulp.xcodeproj/project.pbxproj"; then
    echo "FAIL: PulpSineSynth_HostApp target not present in generated Xcode project"
    echo "      (pulp_add_ios_host_app() likely returned early — check the iOS guard)"
    exit 1
fi
if ! grep -q 'Pulp iOS HostApp: PulpSineSynth_HostApp' "${log}"; then
    echo "FAIL: expected 'Pulp iOS HostApp: PulpSineSynth_HostApp ...' status line from pulp_add_ios_host_app()"
    grep -i 'hostapp\|ios_host' "${log}" >&2 || true
    exit 1
fi

# Actually BUILD the .appex, not just configure. Configure-only smoke
# can't catch link-time regressions like the libc++ `to_chars`
# availability error that landed on iOS-26-SDK hosts.
#
# 2026-05-27: flipped from opt-in to default-on after an iPad walkthrough
# discovered configure-green but link-broken state (pulp-view-core missed
# pulp::audio in its PUBLIC link list; graph_editor_view.hpp unconditionally
# included <pulp/host/signal_graph.hpp> despite pulp::host being skipped on
# iOS). The build step adds ~3–5 min on a cold cache. Set
# PULP_IOS_AUV3_SMOKE_BUILD=0 to fall back to configure-only when
# iterating locally on a slow machine; CI keeps the default behavior.
if [[ "${PULP_IOS_AUV3_SMOKE_BUILD:-1}" == "1" ]]; then
    echo "INFO: PULP_IOS_AUV3_SMOKE_BUILD=1 — proceeding to .appex build"

    build_log="${build_dir}/build.log"
    set +e
    "${timeout_cmd[@]}" cmake --build "${build_dir}/build" \
        --target PulpSineSynth_AUv3 \
        --config Release \
        -- -sdk iphonesimulator \
        >"${build_log}" 2>&1
    build_status=$?
    set -e

    if [[ ${build_status} -eq 124 || ${build_status} -eq 142 ]]; then
        echo "SKIP: PulpSineSynth_AUv3 build exceeded timeout"
        tail -n 80 "${build_log}" >&2
        exit 77
    fi
    if [[ ${build_status} -ne 0 ]]; then
        echo "FAIL: PulpSineSynth_AUv3 build failed (status ${build_status})"
        tail -n 80 "${build_log}" >&2
        exit 1
    fi

    appex_path=$(find "${build_dir}/build" -name "PulpSineSynth.appex" -type d | head -1)
    if [[ -z "${appex_path}" ]]; then
        echo "FAIL: PulpSineSynth.appex not produced after build"
        exit 1
    fi
    if [[ ! -f "${appex_path}/Info.plist" ]]; then
        echo "FAIL: Info.plist missing from built .appex"
        exit 1
    fi
    if ! /usr/bin/plutil -p "${appex_path}/Info.plist" | grep -q 'com.apple.AudioUnit-UI'; then
        echo "FAIL: Info.plist NSExtension does not declare com.apple.AudioUnit-UI"
        /usr/bin/plutil -p "${appex_path}/Info.plist" >&2
        exit 1
    fi
    if ! /usr/bin/plutil -p "${appex_path}/Info.plist" | grep -q 'PulpAUViewController'; then
        echo "FAIL: Info.plist does not name PulpAUViewController as principal class"
        /usr/bin/plutil -p "${appex_path}/Info.plist" >&2
        exit 1
    fi

    # Build the HostApp .app that wraps the .appex too, so the
    # Simulator install path (xcrun simctl install <UDID> <.app>) has a
    # real bundle to install. Smoke-test only — the HostApp's SwiftUI
    # runtime behaviour is validated by the user in the Simulator +
    # GarageBand iOS flow per docs/getting-started/ios-deployment.md.
    hostapp_log="${build_dir}/hostapp_build.log"
    set +e
    # Build the HostApp + the sibling `_Embed` custom target.
    # `pulp_add_ios_host_app()` registers an `add_custom_target(...
    # ALL DEPENDS sentinel)` named `<HostApp>_Embed` whose command
    # copies the `.appex` from `build/AUv3/.../<plugin>.appex` into
    # `<HostApp>.app/PlugIns/<plugin>.appex`. Driving only
    # `--target PulpSineSynth_HostApp` produces the .app shell but
    # skips the embed step, so the bundle ships without an embedded
    # AUv3 — the user installs the HostApp on iPad and GarageBand /
    # AUM never see the plugin in the Audio Unit picker. Build both
    # so the bundle is complete.
    "${timeout_cmd[@]}" cmake --build "${build_dir}/build" \
        --target PulpSineSynth_HostApp \
        --target PulpSineSynth_HostApp_Embed \
        --config Release \
        -- -sdk iphonesimulator \
        >"${hostapp_log}" 2>&1
    hostapp_status=$?
    set -e

    if [[ ${hostapp_status} -eq 124 || ${hostapp_status} -eq 142 ]]; then
        echo "SKIP: PulpSineSynth_HostApp build exceeded timeout"
        tail -n 80 "${hostapp_log}" >&2
        exit 77
    fi
    if [[ ${hostapp_status} -ne 0 ]]; then
        echo "FAIL: PulpSineSynth_HostApp build failed (status ${hostapp_status})"
        tail -n 80 "${hostapp_log}" >&2
        exit 1
    fi

    hostapp_path=$(find "${build_dir}/build" -name "PulpSineSynth.app" -type d | head -1)
    if [[ -z "${hostapp_path}" ]]; then
        echo "FAIL: PulpSineSynth.app not produced after HostApp build"
        exit 1
    fi
    if [[ ! -f "${hostapp_path}/Info.plist" ]]; then
        echo "FAIL: Info.plist missing from built HostApp .app"
        exit 1
    fi
    # The HostApp's Info.plist must mirror the .appex's
    # AudioComponentDescription so AVAudioUnitComponentManager filters
    # resolve. Probe the manufacturer / subtype codes that the
    # PulpSineSynth example wires.
    if ! /usr/bin/plutil -p "${hostapp_path}/Info.plist" | grep -q '"subtype" => "PsSn"'; then
        echo "FAIL: HostApp Info.plist missing AudioComponents.subtype 'PsSn'"
        /usr/bin/plutil -p "${hostapp_path}/Info.plist" >&2
        exit 1
    fi
    # The embedded .appex must live inside the HostApp .app at PlugIns/
    if [[ ! -d "${hostapp_path}/PlugIns/PulpSineSynth.appex" ]]; then
        # iOS bundle layout is flat (.app/PlugIns/...), but the macOS
        # variant nests Contents/. Accept either path for robustness.
        if [[ ! -d "${hostapp_path}/Contents/PlugIns/PulpSineSynth.appex" ]]; then
            echo "FAIL: PulpSineSynth.appex not embedded in HostApp .app under PlugIns/"
            find "${hostapp_path}" -maxdepth 4 -name "*.appex" >&2 || true
            exit 1
        fi
    fi

    echo "OK: pulp_add_ios_auv3() + pulp_add_ios_host_app() iOS Simulator configure + build succeeded"
    echo "    .appex:   ${appex_path}"
    echo "    HostApp:  ${hostapp_path}"
    exit 0
fi

echo "OK: pulp_add_ios_auv3() iOS Simulator configure succeeded"
