function(pulp_default_fetchcontent_cache_root out_var)
    if(DEFINED ENV{PULP_SHARED_FETCHCONTENT_SOURCE_DIR} AND NOT "$ENV{PULP_SHARED_FETCHCONTENT_SOURCE_DIR}" STREQUAL "")
        set(${out_var} "$ENV{PULP_SHARED_FETCHCONTENT_SOURCE_DIR}" PARENT_SCOPE)
        return()
    endif()

    if(NOT "${PULP_SHARED_FETCHCONTENT_SOURCE_DIR}" STREQUAL "")
        set(${out_var} "${PULP_SHARED_FETCHCONTENT_SOURCE_DIR}" PARENT_SCOPE)
        return()
    endif()

    if(APPLE AND DEFINED ENV{HOME})
        set(${out_var} "$ENV{HOME}/Library/Caches/Pulp/fetchcontent-src" PARENT_SCOPE)
    elseif(WIN32)
        if(DEFINED ENV{LOCALAPPDATA} AND NOT "$ENV{LOCALAPPDATA}" STREQUAL "")
            set(${out_var} "$ENV{LOCALAPPDATA}/Pulp/fetchcontent-src" PARENT_SCOPE)
        elseif(DEFINED ENV{USERPROFILE} AND NOT "$ENV{USERPROFILE}" STREQUAL "")
            set(${out_var} "$ENV{USERPROFILE}/AppData/Local/Pulp/fetchcontent-src" PARENT_SCOPE)
        else()
            set(${out_var} "" PARENT_SCOPE)
        endif()
    else()
        if(DEFINED ENV{XDG_CACHE_HOME} AND NOT "$ENV{XDG_CACHE_HOME}" STREQUAL "")
            set(${out_var} "$ENV{XDG_CACHE_HOME}/pulp/fetchcontent-src" PARENT_SCOPE)
        elseif(DEFINED ENV{HOME})
            set(${out_var} "$ENV{HOME}/.cache/pulp/fetchcontent-src" PARENT_SCOPE)
        else()
            set(${out_var} "" PARENT_SCOPE)
        endif()
    endif()
endfunction()

function(pulp_sanitize_cache_suffix input out_var)
    string(REGEX REPLACE "[^A-Za-z0-9._-]+" "_" sanitized "${input}")
    string(REGEX REPLACE "_+" "_" sanitized "${sanitized}")
    string(REGEX REPLACE "^_+|_+$" "" sanitized "${sanitized}")
    set(${out_var} "${sanitized}" PARENT_SCOPE)
endfunction()

function(pulp_register_fetchcontent_source name)
    set(options)
    set(one_value_args DIR REF)
    cmake_parse_arguments(PFC "${options}" "${one_value_args}" "" ${ARGN})

    string(TOUPPER "${name}" upper_name)
    string(TOLOWER "${name}" lower_name)
    set(fetchcontent_var "FETCHCONTENT_SOURCE_DIR_${upper_name}")

    if(DEFINED ${fetchcontent_var} AND NOT "${${fetchcontent_var}}" STREQUAL "")
        if(EXISTS "${${fetchcontent_var}}")
            message(STATUS "Pulp: using explicit source override for ${name}: ${${fetchcontent_var}}")
        else()
            message(WARNING "Pulp: explicit source override for ${name} does not exist: ${${fetchcontent_var}}")
        endif()
        return()
    endif()

    set(explicit_env "PULP_FETCHCONTENT_SOURCE_DIR_${upper_name}")
    set(candidate "")
    if(DEFINED ENV{${explicit_env}} AND NOT "$ENV{${explicit_env}}" STREQUAL "")
        set(candidate "$ENV{${explicit_env}}")
        set(source_label "env:${explicit_env}")
    elseif(PULP_USE_SHARED_FETCHCONTENT_SOURCES)
        pulp_default_fetchcontent_cache_root(cache_root)
        if(NOT "${cache_root}" STREQUAL "")
            if(PFC_REF)
                pulp_sanitize_cache_suffix("${PFC_REF}" cache_suffix)
            endif()
            if(PFC_DIR)
                set(cache_dir "${PFC_DIR}")
            else()
                set(cache_dir "${lower_name}")
            endif()
            if(DEFINED cache_suffix AND NOT "${cache_suffix}" STREQUAL "")
                set(cache_dir "${cache_dir}-${cache_suffix}")
            endif()
            set(candidate "${cache_root}/${cache_dir}")
            set(source_label "shared cache")
        endif()
    endif()

    if("${candidate}" STREQUAL "")
        return()
    endif()

    if(EXISTS "${candidate}")
        set(${fetchcontent_var} "${candidate}" CACHE PATH "Local source override for ${name}" FORCE)
        message(STATUS "Pulp: using ${source_label} for ${name}: ${candidate}")
    elseif(DEFINED source_label AND source_label MATCHES "^env:")
        message(WARNING "Pulp: source override path for ${name} does not exist: ${candidate}")
    endif()
endfunction()

function(pulp_register_wgpu_native_precompiled_source version)
    if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
        set(url_os "windows")
        if(MSVC)
            set(url_compiler "msvc")
        else()
            set(url_compiler "gnu")
        endif()
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(url_os "linux")
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        set(url_os "macos")
    else()
        return()
    endif()

    string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" arch)
    if(arch STREQUAL "amd64")
        set(url_arch "x86_64")
    elseif(arch STREQUAL "x86_64")
        set(url_arch "x86_64")
    elseif(arch STREQUAL "arm64")
        set(url_arch "aarch64")
    elseif(arch STREQUAL "aarch64")
        set(url_arch "aarch64")
    elseif(arch STREQUAL "x86")
        set(url_arch "i686")
    elseif(arch STREQUAL "i686")
        set(url_arch "i686")
    else()
        return()
    endif()

    set(url_name "wgpu-${url_os}-${url_arch}")
    if(DEFINED url_compiler)
        set(url_name "${url_name}-${url_compiler}")
    endif()
    set(url_name "${url_name}-release")

    pulp_register_fetchcontent_source("${url_name}" DIR "${url_name}" REF "${version}")
endfunction()
