#!/usr/bin/env python3
"""Generate a 1:1 pulp::design catalog component from a Figma node.

Codifies the proven faithful-vector lane (see .agents/skills/import-design/SKILL.md
"Figma → Pulp, faithful (1:1)"): export the Figma node's faithful SVG, embed it,
and emit a `DesignFrameView` subclass that renders it 1:1 via SkSVGDOM. This is
the repeatable replacement for hand-painting C++ widgets.

For each component it writes:
  core/view/include/pulp/view/<snake>.hpp        (Class : public DesignFrameView)
  core/view/src/<snake>.cpp                       (ctor decodes embedded SVG)
  core/view/src/<snake>_svg.cpp                   (chunked base64 SVG)
and PRINTS the lines to paste into:
  core/view/CMakeLists.txt (2 sources), design_system.{hpp,cpp} (include+catalog),
  examples/ink-signal-showcase/main.cpp, test/CMakeLists.txt.

Validate the result with pulp-svg-probe + tools/figma-import/verify_region.py.

Usage:
  make_catalog_component.py --name "Channel Strip" --class ChannelStripView \
    --node 182:2 --category containers --usage "Mixer channel strip" \
    [--file-key q9iDYZzg86YrOQKr6I3bY0] [--repo <path>]
"""
import argparse, base64, json, os, re, subprocess, sys, tempfile

FILE_KEY = "q9iDYZzg86YrOQKr6I3bY0"

def snake(s):
    return re.sub(r'(?<!^)(?=[A-Z])', '_', s).lower()

def extract_svg(scene_path):
    raw = open(scene_path).read()
    m = re.search(r'data:image/svg\+xml[^"\\]*', raw)
    if not m:
        sys.exit("no faithful SVG (data:image/svg) in scene — was --faithful-vector on?")
    uri = m.group(0)
    head, _, data = uri.partition(',')
    if 'base64' in head:
        return base64.b64decode(data + '===').decode('utf-8', 'replace')
    import urllib.parse
    return urllib.parse.unquote(data)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True, help='catalog display name, e.g. "Channel Strip"')
    ap.add_argument("--class", dest="cls", required=True, help="C++ class, e.g. ChannelStripView")
    ap.add_argument("--node", required=True, help="Figma node id, e.g. 182:2")
    ap.add_argument("--category", required=True, help="controls|inputs|indicators|navigation|containers|overlays|audio|feedback")
    ap.add_argument("--usage", default="", help="one-line usage note")
    ap.add_argument("--file-key", default=FILE_KEY)
    ap.add_argument("--repo", default=os.getcwd())
    a = ap.parse_args()

    repo = a.repo
    snk = snake(a.cls)
    tools = os.path.join(repo, "tools/import-design")
    tmp = tempfile.mkdtemp(prefix="catgen_")
    scene = os.path.join(tmp, "scene.pulp.json")

    print(f"[1/3] exporting Figma node {a.node} …")
    subprocess.run([sys.executable, os.path.join(tools, "figma_rest_export.py"),
                    "--file-key", a.file_key, "--node", a.node, "--out", scene],
                   check=True)
    svg = extract_svg(scene)
    print(f"      SVG {len(svg)} bytes")

    # 1) embedded SVG data (chunked base64, no >64K literal)
    b64 = base64.b64encode(svg.encode()).decode()
    chunks = [b64[i:i+8000] for i in range(0, len(b64), 8000)]
    arr = ',\n'.join('    "%s"' % c for c in chunks)
    data_cpp = (
        f"// Generated by make_catalog_component.py — embedded faithful SVG for {a.cls}.\n"
        f"// Figma {a.file_key} node {a.node}; rendered 1:1 via DesignFrameView/SkSVGDOM.\n"
        f"#include <string>\n\nnamespace pulp::view::detail {{\n\n"
        f"const char* {snk}_svg_b64() {{\n"
        f"  static const char* const kParts[] = {{\n{arr}\n  }};\n"
        f"  static const std::string kJoined = [] {{ std::string s; for (const char* p : kParts) s += p; return s; }}();\n"
        f"  return kJoined.c_str();\n}}\n\n}}  // namespace pulp::view::detail\n")
    open(os.path.join(repo, f"core/view/src/{snk}_svg.cpp"), "w").write(data_cpp)

    # 2) header
    hpp = (
        f"#pragma once\n\n#include <pulp/view/design_frame_view.hpp>\n\n"
        f"namespace pulp::view {{\n\n"
        f"// {a.name} — Ink & Signal catalog component. Renders the faithful\n"
        f"// Figma-exported SVG 1:1 via DesignFrameView (SkSVGDOM). Generated from\n"
        f"// Figma node {a.node} by tools/import-design/make_catalog_component.py;\n"
        f"// reskin/extend via the faithful-vector lane, never by hand-painting.\n"
        f"class {a.cls} : public DesignFrameView {{\npublic:\n    {a.cls}();\n}};\n\n"
        f"}}  // namespace pulp::view\n")
    open(os.path.join(repo, f"core/view/include/pulp/view/{snk}.hpp"), "w").write(hpp)

    # 3) impl
    cpp = (
        f"#include <pulp/view/{snk}.hpp>\n#include <pulp/runtime/base64.hpp>\n\n#include <string>\n\n"
        f"namespace pulp::view {{\n\n"
        f"namespace detail {{ const char* {snk}_svg_b64(); }}\n\n"
        f"namespace {{\nstd::string decode_{snk}_svg() {{\n"
        f"    if (auto bytes = runtime::base64_decode(detail::{snk}_svg_b64()))\n"
        f"        return std::string(bytes->begin(), bytes->end());\n    return {{}};\n}}\n}}  // namespace\n\n"
        f"{a.cls}::{a.cls}() : DesignFrameView(decode_{snk}_svg(), /*elements=*/{{}}) {{}}\n\n"
        f"}}  // namespace pulp::view\n")
    open(os.path.join(repo, f"core/view/src/{snk}.cpp"), "w").write(cpp)

    print(f"[2/3] wrote core/view/{{include/pulp/view/{snk}.hpp, src/{snk}.cpp, src/{snk}_svg.cpp}}")
    print(f"[3/3] paste these in:\n")
    print(f"# core/view/CMakeLists.txt (with the other src/ entries):")
    print(f"    src/{snk}.cpp\n    src/{snk}_svg.cpp")
    print(f"\n# core/view/include/pulp/design/design_system.hpp (umbrella includes):")
    print(f"#include <pulp/view/{snk}.hpp>")
    print(f"\n# core/view/src/design_system.cpp (catalog vector):")
    print(f'        {{"{a.name}", C::{a.category}, "pulp::view::{a.cls}",')
    print(f'         "pulp/view/{snk}.hpp", "{a.name}",')
    print(f'         "{a.usage}", {{"surface.panel", "accent.primary", "text.primary"}}}},')
    print(f"\n# examples/ink-signal-showcase/main.cpp:")
    print(f"#include <pulp/view/{snk}.hpp>")
    print(f"        add(std::make_unique<{a.cls}>(), kMargin, y, 900.0f, 300.0f); y += 320.0f;")

if __name__ == "__main__":
    main()
