// WinRT MIDI 2.0 (UMP) backend for Windows 11.
//
// The Windows MIDI Services SDK's `Microsoft.Windows.Devices.Midi2`
// projection exposes native MIDI 2.0 endpoints (Universal MIDI Packets),
// `MidiEndpointDeviceWatcher` hotplug, and high-resolution `MidiClock`
// timestamps. The legacy mmeapi backend in winmidi_device.cpp truncates
// MIDI 2.0 UMP, has no hotplug, and requires manual SysEx reassembly. This
// TU is the real WinRT consumer.
//
// Opt-in: it is only compiled when PULP_HAS_WINRT_MIDI is set — a build flag
// the developer enables (see core/midi/CMakeLists.txt) after provisioning the
// Windows MIDI Services SDK's Microsoft.Windows.Devices.Midi2 C++/WinRT
// projection (preferred: the official vcpkg port; see tools/ci/midi2/).
// Without the flag, the linker never sees this object and the mmeapi backend
// stays authoritative.
//
// Why gate rather than auto-detect at compile time: the Midi2 projection
// headers are generated by cppwinrt from a per-SDK-version `.winmd` and ship
// out-of-band with the Windows MIDI Services SDK rather than the base Windows
// SDK. Compile-time opt-in keeps the default CI matrix free of that
// out-of-band dependency.

#if defined(_WIN32) && defined(PULP_HAS_WINRT_MIDI)

#include <pulp/midi/device.hpp>
#include <pulp/midi/ump.hpp>
#include <pulp/midi/ump_conversion.hpp>
#include <pulp/midi/ump_sysex7_reassembler.hpp>
#include <pulp/runtime/log.hpp>

#include <array>
#include <atomic>
#include <memory>
#include <mutex>
#include <string>
#include <vector>

#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
// The Windows MIDI Services projection lives under the Microsoft.* namespace,
// NOT the base-SDK Windows.Devices.Midi2 (which is the older WinRT MIDI 1.0
// API). cppwinrt emits one header per sub-namespace.
#include <winrt/Microsoft.Windows.Devices.Midi2.h>
#include <winrt/Microsoft.Windows.Devices.Midi2.Messages.h>

// Hand-written bootstrap header shipped in the SDK NuGet (build/native/include/
// winmidi/init/...). This is a plain C++ namespace (Microsoft::Windows::
// Devices::Midi2::Initialization), not a WinRT projection — it brings up the
// SDK runtime and reports service availability via MidiDesktopAppSdkInitializer.
#include "winmidi/init/Microsoft.Windows.Devices.Midi2.Initialization.hpp"

namespace pulp::midi::win::winrt_backend {

namespace wf   = ::winrt::Windows::Foundation;
namespace m2   = ::winrt::Microsoft::Windows::Devices::Midi2;
namespace init = ::Microsoft::Windows::Devices::Midi2::Initialization;

// ── Helpers ──────────────────────────────────────────────────────────────

// Process-wide cppwinrt apartment + SDK-runtime init. Idempotent: WinRT
// reference-counts init/uninit per thread, and calling init_apartment more
// than once on the same thread is benign. We init lazily so merely linking
// the backend does not force apartment creation on hosts that never touch
// MIDI.
//
// The Windows MIDI Services SDK additionally requires the desktop-app SDK
// runtime to be brought up (via MidiDesktopAppSdkInitializer) before any
// Microsoft.Windows.Devices.Midi2 activation succeeds. The initializer is
// kept alive for the process lifetime; its destructor shuts the runtime down.
static const std::shared_ptr<init::MidiDesktopAppSdkInitializer>&
sdk_initializer() {
    static std::shared_ptr<init::MidiDesktopAppSdkInitializer> instance = [] {
        auto p = std::make_shared<init::MidiDesktopAppSdkInitializer>();
        if (p && !p->InitializeSdkRuntime()) {
            runtime::log_error("WinRT MIDI: SDK runtime initialization failed");
        }
        return p;
    }();
    return instance;
}

static void ensure_winrt_init() {
    static std::once_flag once;
    std::call_once(once, [] {
        try {
            ::winrt::init_apartment(::winrt::apartment_type::multi_threaded);
        } catch (const ::winrt::hresult_error&) {
            // Already initialised on this thread with a different model, or
            // COM already up — both are fine for our consumer-only usage.
        }
        (void)sdk_initializer();  // bring up the SDK runtime once
    });
}

static std::string hstring_to_utf8(const ::winrt::hstring& hs) {
    return ::winrt::to_string(hs);
}

// Build a UmpPacket from the leading words of a received UMP word stream.
// `words` points at `count` 32-bit words (host byte order, as delivered by
// the Midi2 projection). Returns the number of words consumed, or 0 if the
// stream is malformed / truncated.
static int read_ump_packet(const uint32_t* words, std::size_t count, UmpPacket& out) {
    if (count == 0) return 0;
    const auto mt = static_cast<UmpMessageType>((words[0] >> 28) & 0x0F);
    const int wc = UmpPacket::size_for_type(mt);
    if (static_cast<std::size_t>(wc) > count) return 0;
    out = UmpPacket{};
    out.word_count = wc;
    for (int i = 0; i < wc; ++i) out.words[i] = words[i];
    return wc;
}

// ── WinrtMidiInput ───────────────────────────────────────────────────────

class WinrtMidiInput : public MidiInput {
public:
    ~WinrtMidiInput() override { close(); }

    void set_sysex_callback(MidiSysexCallback cb) override {
        sysex_callback_ = std::move(cb);
    }

    bool open(const std::string& port_id, MidiInputCallback callback) override {
        ensure_winrt_init();
        callback_ = std::move(callback);

        try {
            session_ = m2::MidiSession::Create(L"Pulp MIDI Input");
            if (!session_) {
                runtime::log_error("WinRT MIDI: could not create session");
                return false;
            }

            const ::winrt::hstring endpoint_id = ::winrt::to_hstring(port_id);
            connection_ = session_.CreateEndpointConnection(endpoint_id);
            if (!connection_) {
                runtime::log_error("WinRT MIDI: could not connect to endpoint '{}'", port_id);
                close();
                return false;
            }

            // Subscribe BEFORE Open() so we do not miss the first packets.
            message_token_ = connection_.MessageReceived(
                { this, &WinrtMidiInput::on_message_received });

            if (!connection_.Open()) {
                runtime::log_error("WinRT MIDI: endpoint '{}' failed to open", port_id);
                close();
                return false;
            }

            is_open_ = true;
            return true;
        } catch (const ::winrt::hresult_error& e) {
            runtime::log_error("WinRT MIDI: input open failed: {}",
                               hstring_to_utf8(e.message()));
            close();
            return false;
        }
    }

    void close() override {
        try {
            if (connection_) {
                if (message_token_) {
                    connection_.MessageReceived(message_token_);
                    message_token_ = {};
                }
                if (session_) {
                    session_.DisconnectEndpointConnection(connection_.ConnectionId());
                }
            }
        } catch (const ::winrt::hresult_error&) {
            // Best-effort teardown — endpoint may already be gone (unplug).
        }
        connection_ = nullptr;
        session_ = nullptr;
        is_open_ = false;
    }

    bool is_open() const override { return is_open_; }

private:
    // Fired on a WinRT thread-pool thread. Decode the UMP words, convert
    // channel-voice packets to MIDI 1.0 events for the short-message
    // callback, and surface complete SysEx (UMP Data type 0x3) to the
    // sysex callback via the running 7-bit reassembly buffer.
    void on_message_received(const m2::IMidiMessageReceivedEventSource&,
                             const m2::MidiMessageReceivedEventArgs& args) {
        try {
            // FillWords copies the packet's UMP words into a fixed buffer so we
            // never touch projection memory after the event returns. The
            // Microsoft.Windows.Devices.Midi2 projection takes the four words by
            // out-reference (not an array) and returns the count actually filled
            // (0..4): `UInt8 FillWords(out UInt32 w0, out UInt32 w1, out UInt32
            // w2, out UInt32 w3)`.
            std::array<uint32_t, 4> buf{};
            const uint32_t filled =
                args.FillWords(buf[0], buf[1], buf[2], buf[3]);
            const double ts = ump_timestamp_seconds(args.Timestamp());

            std::size_t i = 0;
            while (i < filled) {
                UmpPacket packet;
                const int consumed = read_ump_packet(
                    buf.data() + i, static_cast<std::size_t>(filled) - i, packet);
                if (consumed == 0) break;
                i += static_cast<std::size_t>(consumed);
                dispatch_packet(packet, ts);
            }
        } catch (const ::winrt::hresult_error&) {
            // Drop a malformed event rather than tear down the connection.
        }
    }

    void dispatch_packet(const UmpPacket& packet, double ts) {
        if (packet.message_type() == UmpMessageType::DataSysEx) {
            // Reassemble UMP Type-0x3 sysex7 via the shared, unit-tested
            // state machine. It emits the raw payload (no F0/F7 framing);
            // we wrap it to F0..F7 to match the other backends' contract
            // (mmeapi MIM_LONGDATA / ALSA deliver framed SysEx).
            //
            // SysEx7 reassembly is per-stream state, and UMP SysEx7 streams
            // can interleave across the 16 UMP groups. Keep one reassembler
            // per group so a Start on group 1 cannot reset/corrupt an
            // in-flight stream on group 0. The completion callback fires
            // synchronously inside feed_packet, so a single last_sysex_ts_
            // set immediately before the call stays correct.
            last_sysex_ts_ = ts;
            sysex_reassemblers_[packet.group() & 0x0F].feed_packet(
                packet.words[0], packet.words[1],
                &WinrtMidiInput::on_sysex_complete, this);
            return;
        }

        // Channel-voice (MIDI 1.0 or MIDI 2.0) → MIDI 1.0 short message.
        MidiEvent evt{};
        if (callback_ && ump_to_midi1_event(packet, evt)) {
            evt.timestamp = ts;
            callback_(evt);
        }
    }

    static void on_sysex_complete(const std::vector<uint8_t>& payload, void* user) {
        auto* self = static_cast<WinrtMidiInput*>(user);
        if (!self->sysex_callback_) return;
        std::vector<uint8_t> framed;
        framed.reserve(payload.size() + 2);
        framed.push_back(0xF0);
        framed.insert(framed.end(), payload.begin(), payload.end());
        framed.push_back(0xF7);
        self->sysex_callback_(framed, self->last_sysex_ts_);
    }

    // Convert a MidiClock timestamp (QPC ticks) to seconds-since-open so the
    // value matches the mmeapi / CoreMIDI / ALSA backends' contract.
    double ump_timestamp_seconds(uint64_t ts_ticks) {
        const uint64_t freq = midi_clock_frequency();
        if (freq == 0) return 0.0;
        if (!have_origin_) {
            origin_ticks_ = ts_ticks;
            have_origin_ = true;
        }
        const uint64_t delta = ts_ticks - origin_ticks_;
        return static_cast<double>(delta) / static_cast<double>(freq);
    }

    static uint64_t midi_clock_frequency() {
        static const uint64_t freq = [] {
            try { return m2::MidiClock::TimestampFrequency(); }
            catch (...) { return uint64_t{0}; }
        }();
        return freq;
    }

    m2::MidiSession            session_{nullptr};
    m2::MidiEndpointConnection connection_{nullptr};
    ::winrt::event_token       message_token_{};
    MidiInputCallback          callback_;
    MidiSysexCallback          sysex_callback_;
    // One reassembler per UMP group (0..15) — SysEx7 streams interleave
    // across groups, so a single shared reassembler would corrupt them.
    std::array<UmpSysex7Reassembler, 16> sysex_reassemblers_{};
    double                     last_sysex_ts_ = 0.0;
    bool                       is_open_ = false;
    bool                       have_origin_ = false;
    uint64_t                   origin_ticks_ = 0;
};

// ── WinrtMidiOutput ──────────────────────────────────────────────────────

class WinrtMidiOutput : public MidiOutput {
public:
    ~WinrtMidiOutput() override { close(); }

    bool open(const std::string& port_id) override {
        ensure_winrt_init();
        try {
            session_ = m2::MidiSession::Create(L"Pulp MIDI Output");
            if (!session_) {
                runtime::log_error("WinRT MIDI: could not create output session");
                return false;
            }
            const ::winrt::hstring endpoint_id = ::winrt::to_hstring(port_id);
            connection_ = session_.CreateEndpointConnection(endpoint_id);
            if (!connection_ || !connection_.Open()) {
                runtime::log_error("WinRT MIDI: could not open output endpoint '{}'", port_id);
                close();
                return false;
            }
            is_open_ = true;
            return true;
        } catch (const ::winrt::hresult_error& e) {
            runtime::log_error("WinRT MIDI: output open failed: {}",
                               hstring_to_utf8(e.message()));
            close();
            return false;
        }
    }

    void close() override {
        try {
            if (connection_ && session_) {
                session_.DisconnectEndpointConnection(connection_.ConnectionId());
            }
        } catch (const ::winrt::hresult_error&) {
            // Endpoint may already be gone.
        }
        connection_ = nullptr;
        session_ = nullptr;
        is_open_ = false;
    }

    bool is_open() const override { return is_open_; }

    void send(const MidiEvent& event) override {
        if (!connection_) return;
        try {
            // Promote the MIDI 1.0 short message to a MIDI 2.0 channel-voice
            // UMP so we transmit at native resolution on the MIDI 2.0 wire.
            const UmpPacket packet = midi1_event_to_ump2(event, /*group=*/0);
            std::array<uint32_t, 4> words = packet.words;
            // SendSingleMessageWordArray(UInt64 timestamp, UInt32 startIndex,
            // UInt8 wordCount, UInt32[] words) — wordCount is UInt8 in the
            // projection, so cast to uint8_t (not uint32_t) to avoid an MSVC
            // narrowing warning under /WX.
            connection_.SendSingleMessageWordArray(
                /*timestamp=*/0,  // 0 == send immediately
                /*startIndex=*/0,
                static_cast<uint8_t>(packet.word_count),
                words);
        } catch (const ::winrt::hresult_error&) {
            // Drop on transient send failure (e.g. endpoint unplugged).
        }
    }

private:
    m2::MidiSession            session_{nullptr};
    m2::MidiEndpointConnection connection_{nullptr};
    bool                       is_open_ = false;
};

// ── WinrtMidiSystem ──────────────────────────────────────────────────────

class WinrtMidiSystem : public MidiSystem {
public:
    WinrtMidiSystem() { ensure_winrt_init(); }

    ~WinrtMidiSystem() override {
        // Drop the watcher (which captures `this`) before members tear down.
        stop_watcher();
    }

    std::vector<MidiPortInfo> enumerate_inputs() override {
        return enumerate_endpoints(/*want_input=*/true);
    }

    std::vector<MidiPortInfo> enumerate_outputs() override {
        return enumerate_endpoints(/*want_input=*/false);
    }

    std::unique_ptr<MidiInput> create_input() override {
        return std::make_unique<WinrtMidiInput>();
    }

    std::unique_ptr<MidiOutput> create_output() override {
        return std::make_unique<WinrtMidiOutput>();
    }

    // Hotplug: a MidiEndpointDeviceWatcher fires Added/Removed/Updated as
    // MIDI endpoints appear and disappear. Each transition fires the stored
    // port-change callback (which may run on a WinRT thread). Passing
    // nullptr stops the watcher.
    void set_port_change_callback(PortChangeCallback cb) override {
        const bool want_watch = static_cast<bool>(cb);
        {
            std::lock_guard<std::mutex> lock(cb_mutex_);
            port_change_cb_ = std::move(cb);
        }
        if (want_watch) start_watcher();
        else            stop_watcher();
    }

private:
    void start_watcher() {
        if (watcher_) return;
        try {
            watcher_ = m2::MidiEndpointDeviceWatcher::Create(
                m2::MidiEndpointDeviceInformationFilters::AllStandardEndpoints);
            if (!watcher_) return;

            added_token_ = watcher_.Added(
                [this](auto&&, auto&&) { fire_port_change(); });
            removed_token_ = watcher_.Removed(
                [this](auto&&, auto&&) { fire_port_change(); });
            updated_token_ = watcher_.Updated(
                [this](auto&&, auto&&) { fire_port_change(); });

            watcher_.Start();
        } catch (const ::winrt::hresult_error& e) {
            runtime::log_error("WinRT MIDI: device watcher failed to start: {}",
                               hstring_to_utf8(e.message()));
            watcher_ = nullptr;
        }
    }

    void stop_watcher() {
        if (!watcher_) return;
        try {
            if (added_token_)   { watcher_.Added(added_token_);     added_token_ = {}; }
            if (removed_token_) { watcher_.Removed(removed_token_); removed_token_ = {}; }
            if (updated_token_) { watcher_.Updated(updated_token_); updated_token_ = {}; }
            watcher_.Stop();
        } catch (const ::winrt::hresult_error&) {
            // Best-effort.
        }
        watcher_ = nullptr;
    }

    void fire_port_change() {
        PortChangeCallback cb;
        {
            std::lock_guard<std::mutex> lock(cb_mutex_);
            cb = port_change_cb_;
        }
        if (cb) cb();
    }

    std::vector<MidiPortInfo> enumerate_endpoints(bool want_input) {
        std::vector<MidiPortInfo> ports;
        try {
            const auto found = m2::MidiEndpointDeviceInformation::FindAll(
                m2::MidiEndpointDeviceInformationSortOrder::Name,
                m2::MidiEndpointDeviceInformationFilters::AllStandardEndpoints);

            for (const auto& dev : found) {
                // A UMP endpoint is bidirectional; expose it under whichever
                // direction the caller asked for. The endpoint id is the
                // stable handle passed back to open().
                MidiPortInfo info;
                info.id = hstring_to_utf8(dev.EndpointDeviceId());
                info.name = hstring_to_utf8(dev.Name());
                info.is_input = want_input;
                info.is_output = !want_input;
                ports.push_back(std::move(info));
            }
        } catch (const ::winrt::hresult_error& e) {
            runtime::log_error("WinRT MIDI: enumeration failed: {}",
                               hstring_to_utf8(e.message()));
        }
        return ports;
    }

    m2::MidiEndpointDeviceWatcher watcher_{nullptr};
    ::winrt::event_token          added_token_{};
    ::winrt::event_token          removed_token_{};
    ::winrt::event_token          updated_token_{};
    std::mutex                    cb_mutex_;
    PortChangeCallback            port_change_cb_;
};

// Runtime availability probe. The build flag means the developer chose to
// link the WinRT MIDI 2.0 projection; this confirms the Midi2 service is
// actually usable on the running machine (Windows 11 with Windows MIDI
// Services installed). Returns false on older Windows so callers fall back
// to the mmeapi backend.
bool winrt_midi_available() {
    ensure_winrt_init();
    try {
        // MidiDesktopAppSdkInitializer::EnsureServiceAvailable() reports
        // whether the Windows MIDI Services transport is present and
        // responding. Treat a missing initializer or any exception as
        // "unavailable" so callers fall back to the mmeapi backend.
        const auto& sdk = sdk_initializer();
        return sdk && sdk->EnsureServiceAvailable();
    } catch (const ::winrt::hresult_error&) {
        return false;
    }
}

std::unique_ptr<MidiSystem> create_winrt_midi_system() {
    return std::make_unique<WinrtMidiSystem>();
}

}  // namespace pulp::midi::win::winrt_backend

#else  // !(_WIN32 && PULP_HAS_WINRT_MIDI)

// When PULP_HAS_WINRT_MIDI is unset (the default), keep the probe symbol
// resolved so the mmeapi factory in winmidi_device.cpp can branch on it
// without its own build-flag gate. The system factory is intentionally
// absent here — only the WinRT-enabled build provides it, and the mmeapi
// factory only calls it when winrt_midi_available() returns true.
#include <pulp/midi/device.hpp>

namespace pulp::midi::win::winrt_backend {
bool winrt_midi_available() { return false; }
}  // namespace pulp::midi::win::winrt_backend

#endif
