//
// Minimal SwiftUI host for an AUv3 Pulp plug-in (issue #250).
//
// Loads the plug-in's audio unit via AVAudioUnitComponentManager,
// instantiates an AVAudioEngine with a sampler source → the Pulp AU
// → output. The view exposes a play/stop button and lists the
// plug-in's parameters via the AVAudioUnit's parameterTree so the
// user can verify the extension loads without opening a full DAW.
//
// Discovery strategy: read the embedded AUv3's exact
// AudioComponentDescription back from the HostApp's own Info.plist
// `AudioComponents[0]` entry, which is generated by
// `pulp_add_ios_host_app()` from the AUv3 extension target's
// type/subtype/manufacturer/version. That makes the picker
// deterministic when more than one Pulp AUv3 is installed on the
// device or simulator — the HostApp will always instantiate the
// extension it ships with, not whatever Pulp AUv3 happens to register
// first.
//
// If the Info.plist `AudioComponents` entry is missing or malformed
// (developer overrode the template without providing the descriptor)
// the host falls back to the previous manufacturer-only filter so the
// template still surfaces a usable plug-in for triage instead of
// failing silently.
//

import SwiftUI
import AVFoundation
import AudioToolbox
import CoreAudioTypes
#if os(iOS)
import UIKit
import CoreAudioKit
#endif

#if os(iOS) || os(macOS)

@available(iOS 15.0, macOS 12.0, *)
struct ContentView: View {
    @StateObject private var host = PulpAUv3Host()

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text(host.componentName ?? "(no Pulp AUv3 found — check Info.plist)")
                .font(.headline)

            HStack(spacing: 12) {
                Button(host.isPlaying ? "Stop" : "Play") {
                    host.toggle()
                }
                .disabled(host.audioUnit == nil)
                .buttonStyle(.borderedProminent)

                if !host.parameters.isEmpty {
                    Text("\(host.parameters.count) parameter(s)")
                        .foregroundStyle(.secondary)
                }
            }

            ForEach(host.parameters, id: \.address) { p in
                ParameterRow(param: p)
            }

            // Mount the AUv3 extension's own view inside the HostApp so
            // the Skia/Dawn-rendered plug-in editor
            // (PulpAUViewController on iOS) is actually visible in the
            // SwiftUI shell, not just instantiated for audio render.
            //
            // Without this block the AU can load and render to its own UIView,
            // but the HostApp window stays a SwiftUI-only screen with no
            // visible editor.
            #if os(iOS)
            // Let the editor fill the whole pane below the controls instead of
            // sitting at its intrinsic preferredContentSize (the plug-in's
            // design size, e.g. the Three.js demo's 540×720 shell) pinned to
            // the top-left. `maxWidth/maxHeight: .infinity` hands the AUv3
            // editor the full available rectangle; the editor's own host
            // (au_view_controller_ios.mm) then scales its fixed design viewport
            // up to those bounds. Generic across every iOS AUv3 example —
            // minHeight keeps a sensible floor when the pane is short.
            PulpAUv3EditorView(host: host)
                .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
                .frame(minHeight: 280)
                .background(Color.black.opacity(0.04))
                .cornerRadius(8)
                .padding(.top, 4)
            #endif

            Spacer(minLength: 0)
        }
        .padding()
        .onAppear {
            host.discover()
            // Auto-Play after 1.5s so the audio path lights up without a
            // tap — useful for `simctl io booted recordVideo` smoke runs.
            DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
                if !host.isPlaying && host.audioUnit != nil { host.toggle() }
            }

            // First-install registration race: iOS may not have scanned a
            // newly-installed .appex yet when the host's .onAppear fires.
            // Discover() returns 0 matches in that window, and without a
            // retry the host stays stuck on "(no Pulp AUv3 found)" until
            // the user kills + relaunches the app — which is the exact UX
            // failure seen during fresh devicectl installs. Wire two
            // recovery paths:
            //
            // 1. Observe `AVAudioUnitComponentManager`'s
            //    `RegistrationsChangedNotification` (Apple's documented
            //    signal that the AU component registry changed) and
            //    re-discover when it fires. Covers the happy path where
            //    iOS finishes its scan within the app's foreground
            //    session.
            //
            // 2. Polling fallback every 1s for the first 60s after launch
            //    — guards against quirks where iOS fires the notification
            //    on a different observer, or doesn't fire at all on the
            //    first foreground after install. Stops as soon as
            //    discovery finds the embedded extension.
            let nc = NotificationCenter.default
            let regChanged = NSNotification.Name(
                "AVAudioUnitComponentManagerRegistrationsChangedNotification")
            nc.addObserver(forName: regChanged, object: nil, queue: nil) { _ in
                Task { @MainActor in
                    if host.audioUnit == nil { host.discover() }
                }
            }
            // Polling fallback for the first 60s, in case the
            // notification doesn't fire or fires before our observer
            // is set up. iPad PluginKit registration after a fresh
            // `devicectl install` can take 30-60s on first launch
            // even though the .appex is on disk; without an
            // aggressive poll the host stays stuck on "(no Pulp AUv3
            // found)" past the user's patience threshold. Each tick
            // is a separate Task hop to the main actor so Swift 6
            // strict-concurrency is happy.
            Task { @MainActor in
                for _ in 0..<60 {
                    try? await Task.sleep(nanoseconds: 1_000_000_000)
                    if host.audioUnit != nil { return }
                    host.discover()
                }
            }
        }
    }
}

// One parameter row. The earlier inline `Slider(value: Binding(get/set))`
// bound straight to `AUParameter.value`, which SwiftUI does not observe — so
// dragging wrote the AU param but never re-rendered, leaving the thumb and the
// "0.00" readout stuck. Mirroring the value in `@State` makes the slider move
// and the number update live as you drag, while `onChange` writes through to
// the AU parameter, and an observer reflects host/automation changes back.
@available(iOS 15.0, macOS 12.0, *)
private struct ParameterRow: View {
    let param: AUParameter
    @State private var value: Double
    @State private var observerToken: AUParameterObserverToken?

    init(param: AUParameter) {
        self.param = param
        _value = State(initialValue: Double(param.value))
    }

    var body: some View {
        HStack {
            Text(param.displayName).frame(maxWidth: .infinity, alignment: .leading)
            Slider(value: $value, in: Double(param.minValue)...Double(param.maxValue))
                .onChange(of: value) { newValue in
                    // Write through as the user drags. Pass our own observer
                    // token as originator so the observer below doesn't echo
                    // this back into `value` and fight the gesture.
                    param.setValue(AUValue(newValue), originator: observerToken)
                }
            Text(String(format: "%.2f", value))
                .frame(width: 56, alignment: .trailing)
                .monospacedDigit()
        }
        .onAppear {
            value = Double(param.value)
            observerToken = param.token(byAddingParameterObserver: { _, newValue in
                Task { @MainActor in value = Double(newValue) }
            })
        }
        .onDisappear {
            if let token = observerToken {
                param.removeParameterObserver(token)
                observerToken = nil
            }
        }
    }
}

#if os(iOS)

// SwiftUI bridge that hosts the AUv3 extension's editor
// (PulpAUViewController) inside the HostApp via UIViewControllerRepresentable.
// The extension is loaded out-of-process
// (PulpAUv3Host.discover()), so AVAudioUnit.requestViewController fetches
// the view controller across the XPC connection. We park the returned
// VC inside a container UIViewController so SwiftUI's layout pass can
// drive its preferredContentSize without rebuilding the AU.
//
// When the AU hasn't been instantiated yet (or the request returns nil),
// the placeholder UI surfaces an obvious "(loading…)" / "(no AUv3 editor)"
// label so a failed mount doesn't look like a black-screen render bug.
@available(iOS 15.0, *)
struct PulpAUv3EditorView: UIViewControllerRepresentable {
    @ObservedObject var host: PulpAUv3Host

    // Coordinator carries the observer token and a host reference so
    // dismantleUIViewController (a static method) can unregister the
    // observer when SwiftUI tears down this representable. Without
    // that pairing, `host.installEditorObserver { ... }` strongly
    // captures the container VC; every SwiftUI rebuild (orientation
    // change, scene reset, iPad split-view shuffle) appends a new
    // closure to the host's observer list and never removes the old
    // one, so dead container VCs are kept alive for the lifetime of
    // the `@StateObject` host.
    func makeCoordinator() -> Coordinator { Coordinator() }

    func makeUIViewController(context: Context) -> EditorContainerViewController {
        let vc = EditorContainerViewController()
        let token = host.installEditorObserver { [weak vc] editorVC in
            vc?.setEditor(editorVC)
        }
        context.coordinator.host = host
        context.coordinator.observerToken = token
        return vc
    }

    func updateUIViewController(_ uiViewController: EditorContainerViewController, context: Context) {
        // No-op — the container observes host.editorViewController updates
        // through installEditorObserver.
    }

    static func dismantleUIViewController(
        _ uiViewController: EditorContainerViewController,
        coordinator: Coordinator
    ) {
        uiViewController.setEditor(nil)
        if let token = coordinator.observerToken {
            coordinator.host?.removeEditorObserver(token)
        }
        coordinator.observerToken = nil
        coordinator.host = nil
    }

    final class Coordinator {
        var host: PulpAUv3Host?
        var observerToken: Int?
    }

    final class EditorContainerViewController: UIViewController {
        private weak var editor: UIViewController?
        private let placeholder = UILabel()

        override func viewDidLoad() {
            super.viewDidLoad()
            view.backgroundColor = .clear
            placeholder.text = "(AUv3 editor loading…)"
            placeholder.textAlignment = .center
            placeholder.textColor = .secondaryLabel
            placeholder.font = .preferredFont(forTextStyle: .body)
            placeholder.translatesAutoresizingMaskIntoConstraints = false
            view.addSubview(placeholder)
            NSLayoutConstraint.activate([
                placeholder.centerXAnchor.constraint(equalTo: view.centerXAnchor),
                placeholder.centerYAnchor.constraint(equalTo: view.centerYAnchor),
            ])
        }

        func setEditor(_ vc: UIViewController?) {
            // Detach prior editor cleanly (UIKit child-VC contract).
            if let prior = editor {
                prior.willMove(toParent: nil)
                prior.view.removeFromSuperview()
                prior.removeFromParent()
            }
            editor = vc
            guard let vc = vc else {
                placeholder.text = "(no AUv3 editor — extension may have failed to load)"
                placeholder.isHidden = false
                return
            }
            placeholder.isHidden = true
            addChild(vc)
            vc.view.translatesAutoresizingMaskIntoConstraints = false
            view.addSubview(vc.view)
            NSLayoutConstraint.activate([
                vc.view.leadingAnchor.constraint(equalTo: view.leadingAnchor),
                vc.view.trailingAnchor.constraint(equalTo: view.trailingAnchor),
                vc.view.topAnchor.constraint(equalTo: view.topAnchor),
                vc.view.bottomAnchor.constraint(equalTo: view.bottomAnchor),
            ])
            vc.didMove(toParent: self)
            print("PULP_EDITOR_MOUNTED: AUv3 view controller attached to HostApp container")
        }
    }
}

#endif

@available(iOS 15.0, macOS 12.0, *)
@MainActor
final class PulpAUv3Host: ObservableObject {
    @Published var componentName: String? = nil
    @Published var parameters: [AUParameter] = []
    @Published var isPlaying = false
    var audioUnit: AUAudioUnit?
    // Set true between calling AVAudioUnit.instantiate and its callback
    // landing. Polling retries in ContentView.onAppear consult this so
    // they don't fire concurrent instantiations that would each create
    // a fresh AU + tear down the editor view between cycles.
    private var instantiationInFlight: Bool = false

#if os(iOS)
    // Editor view controller fetched via AUAudioUnit.requestViewController.
    // We hold the most recent VC and
    // notify subscribers so the SwiftUI container can re-mount when the
    // extension finishes loading after the HostApp view tree exists.
    //
    // Observer storage is keyed by an opaque token so SwiftUI's
    // dismantleUIViewController hook can unregister cleanly on view
    // rebuild — otherwise the closure strongly retains the container
    // VC and every rebuild leaks one VC for the lifetime of this
    // `@StateObject` host.
    @Published private(set) var editorViewController: UIViewController?
    private var editorObservers: [Int: (UIViewController?) -> Void] = [:]
    private var nextEditorObserverToken: Int = 0

    @discardableResult
    func installEditorObserver(_ block: @escaping (UIViewController?) -> Void) -> Int {
        let token = nextEditorObserverToken
        nextEditorObserverToken += 1
        editorObservers[token] = block
        block(editorViewController)
        return token
    }

    func removeEditorObserver(_ token: Int) {
        editorObservers.removeValue(forKey: token)
    }

    fileprivate func setEditorVC(_ vc: UIViewController?) {
        editorViewController = vc
        for obs in editorObservers.values { obs(vc) }
    }
#endif

    // Pulp manufacturer code: 'Pulp' = 0x50756C70. Used as a
    // last-resort fallback when the HostApp Info.plist doesn't carry
    // an `AudioComponents[0]` entry to disambiguate.
    private let pulpManufacturerCode: OSType = 0x50_75_6C_70

    private let engine = AVAudioEngine()
    private var node: AVAudioUnit?
    private var midiBlock: AUScheduleMIDIEventBlock?

    // Read the embedded AUv3 extension's AudioComponentDescription back
    // from the HostApp's own Info.plist. `pulp_add_ios_host_app()`
    // mirrors the extension's type/subtype/manufacturer/version four-CCs
    // into `AudioComponents[0]` at configure time, so this is the
    // single source of truth that disambiguates which Pulp AUv3 the
    // HostApp ships with when several Pulp plug-ins are installed on
    // the same device or simulator.
    //
    // Returns nil when the entry is missing or malformed; callers
    // fall back to a manufacturer-only filter in that case so the
    // template still surfaces something for triage instead of going
    // silent.
    static func embeddedDescriptor() -> AudioComponentDescription? {
        guard let entries = Bundle.main.object(forInfoDictionaryKey: "AudioComponents") as? [[String: Any]],
              let first = entries.first,
              let typeStr = first["type"] as? String,
              let subtypeStr = first["subtype"] as? String,
              let manufacturerStr = first["manufacturer"] as? String,
              let typeCode = fourCC(from: typeStr),
              let subtypeCode = fourCC(from: subtypeStr),
              let manufacturerCode = fourCC(from: manufacturerStr) else {
            return nil
        }
        var desc = AudioComponentDescription()
        desc.componentType = typeCode
        desc.componentSubType = subtypeCode
        desc.componentManufacturer = manufacturerCode
        desc.componentFlags = 0
        desc.componentFlagsMask = 0
        return desc
    }

    // Convert a four-character code string ("aumu", "PsSn", "Pulp")
    // into the OSType the Audio Unit APIs expect. Returns nil for
    // anything that isn't exactly four ASCII bytes.
    private static func fourCC(from s: String) -> OSType? {
        let bytes = Array(s.utf8)
        guard bytes.count == 4 else { return nil }
        return (OSType(bytes[0]) << 24) | (OSType(bytes[1]) << 16) | (OSType(bytes[2]) << 8) | OSType(bytes[3])
    }

    // Inverse of fourCC(from:) for log lines. Renders four bytes of an
    // OSType back as the ASCII four-character code the AU APIs use.
    fileprivate func fourCCString(_ code: OSType) -> String {
        let bytes: [UInt8] = [
            UInt8((code >> 24) & 0xff),
            UInt8((code >> 16) & 0xff),
            UInt8((code >> 8) & 0xff),
            UInt8(code & 0xff),
        ]
        if let s = String(bytes: bytes, encoding: .ascii) { return s }
        return String(format: "0x%08x", code)
    }

    func discover() {
        // Idempotency: if the AU is already instantiated, or
        // instantiation is in flight, skip. Without this the polling
        // fallback in ContentView.onAppear (added 2026-05-30 to fix
        // the first-install registration race) would re-call
        // `AVAudioUnit.instantiate(...)` every 1s — each call creates
        // a fresh AudioUnit, which tears down the AUv3's editor view
        // and stops Three.js from completing a render pass. See
        // .agents/skills/auv3 SKILL.md "First-install discovery race"
        // section for context.
        if audioUnit != nil { return }
        if instantiationInFlight { return }
        instantiationInFlight = true

        // Prefer the exact descriptor mirrored from the embedded AUv3
        // (HostApp Info.plist → AudioComponents[0]) so the picker is
        // deterministic across installed Pulp plug-ins. Fall back to
        // a manufacturer-only filter when the entry is missing — that
        // path preserves the previous behaviour for debugging-only
        // HostApps that strip the AudioComponents key.
        let manager = AVAudioUnitComponentManager.shared()
        let allUnits = manager.components(matching: AudioComponentDescription())

        let embedded = Self.embeddedDescriptor()
        let pulpUnits: [AVAudioUnitComponent]
        let matchMode: String
        if let target = embedded {
            pulpUnits = allUnits.filter { c in
                let d = c.audioComponentDescription
                return d.componentType == target.componentType
                    && d.componentSubType == target.componentSubType
                    && d.componentManufacturer == target.componentManufacturer
            }
            matchMode = String(
                format: "exact descriptor type=%@ subtype=%@ mfr=%@",
                fourCCString(target.componentType),
                fourCCString(target.componentSubType),
                fourCCString(target.componentManufacturer))
        } else {
            pulpUnits = allUnits.filter { $0.audioComponentDescription.componentManufacturer == pulpManufacturerCode }
            matchMode = "fallback manufacturer-only (no AudioComponents[0] in Info.plist)"
        }

        // PULP_DISCOVER prints are deliberate triage helpers — keep them.
        // When the audio path silently fails, grep `PULP_` in the launch
        // log to identify which step in the chain broke. See
        // `.agents/skills/auv3/SKILL.md` "iOS AUv3 diagnostic recipe".
        print("PULP_DISCOVER_ALL: \(allUnits.count) total AUv3 components on this system")
        print("PULP_DISCOVER_MODE: \(matchMode)")
        print("PULP_DISCOVER: matching Pulp components=\(pulpUnits.count)")
        for c in pulpUnits {
            print("PULP_DISCOVER:   - name=\(c.name) type=\(c.typeName) mfr=\(c.manufacturerName)")
        }

        guard let first = pulpUnits.first else {
            print("PULP_DISCOVER: no matching Pulp AUv3 found — extension may have failed to register, or HostApp Info.plist AudioComponents[0] does not match the embedded .appex")
            instantiationInFlight = false
            return
        }
        let firstName = first.name
        Task { @MainActor in self.componentName = "Found: \(firstName)" }

        let desc = first.audioComponentDescription

        // iOS cannot load AUv3 extensions in-process; must use
        // .loadOutOfProcess. The default `[]` returns OSStatus 4
        // ("Exec format" / instantiate failed). See Apple's
        // "Incorporating Audio Effects and Instruments" sample.
        #if os(iOS)
        let instOptions: AudioComponentInstantiationOptions = .loadOutOfProcess
        #else
        let instOptions: AudioComponentInstantiationOptions = []
        #endif

        AVAudioUnit.instantiate(with: desc, options: instOptions) { [weak self] node, error in
            if let err = error { print("PULP_INSTANTIATE_ERROR: \(err)") }
            guard let self = self, let node = node, error == nil else {
                print("PULP_INSTANTIATE: bailed (node=\(String(describing: node)) error=\(String(describing: error)))")
                if let self = self {
                    Task { @MainActor in self.instantiationInFlight = false }
                }
                return
            }
            Task { @MainActor in
                self.instantiationInFlight = false
                self.node = node
                self.audioUnit = node.auAudioUnit
                self.componentName = node.auAudioUnit.componentName
                print("PULP_INSTANTIATE_OK: \(node.auAudioUnit.componentName ?? "(nil)")")
                if let tree = node.auAudioUnit.parameterTree {
                    self.parameters = tree.allParameters
                }
                self.engine.attach(node)

                // Effects need a source feeding them — otherwise they
                // silently process zeros. Instruments (aumu) drive
                // themselves via MIDI events sent below in toggle().
                if desc.componentType != kAudioUnitType_MusicDevice {
                    self.engine.connect(self.engine.inputNode, to: node, format: nil)
                }
                self.engine.connect(node, to: self.engine.mainMixerNode, format: nil)

                // For an instrument (aumu), wire a MIDI event block so
                // toggle() can send a sustained note. Pattern from
                // Apple's SimplePlayEngine.InstrumentPlayer.
                if desc.componentType == kAudioUnitType_MusicDevice {
                    self.midiBlock = node.auAudioUnit.scheduleMIDIEventBlock
                    print("PULP_MIDI_BLOCK: \(self.midiBlock != nil ? "ready" : "unavailable")")
                }

                // Fetch the extension's view controller. AUv3 on iOS surfaces
                // UI as a UIViewController via
                // requestViewControllerWithCompletionHandler:; SwiftUI's
                // UIViewControllerRepresentable hosts the result so the
                // Skia/Dawn-rendered plug-in editor (PulpAUViewController)
                // is visible in the HostApp window, not just running
                // headlessly behind the audio render block.
                #if os(iOS)
                node.auAudioUnit.requestViewController { vc in
                    DispatchQueue.main.async {
                        print("PULP_EDITOR_REQUESTED: requestViewController -> \(vc == nil ? "nil" : "present")")
                        self.setEditorVC(vc)
                    }
                }
                #endif
            }
        }
    }

    func sendNote(noteOn: Bool, key: UInt8 = 60, velocity: UInt8 = 100) {
        guard let block = midiBlock else { print("PULP_NOTE: no midiBlock"); return }
        let status: UInt8 = noteOn ? 0x90 : 0x80
        let vel: UInt8 = noteOn ? velocity : 0
        let bytes = UnsafeMutablePointer<UInt8>.allocate(capacity: 3)
        bytes[0] = status; bytes[1] = key; bytes[2] = vel
        block(AUEventSampleTimeImmediate, 0, 3, bytes)
        bytes.deallocate()
        print("PULP_NOTE: \(noteOn ? "ON" : "OFF") key=\(key) vel=\(vel)")
    }

    func toggle() {
        if isPlaying {
            sendNote(noteOn: false)
            engine.stop()
            isPlaying = false
        } else {
            do {
                try engine.start()
                isPlaying = true
                // Trigger a sustained C4 (note 60) for the instrument
                // path so we hear something when Play is tapped. Effects
                // don't need MIDI — they're fed by inputNode in discover().
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) { [weak self] in
                    self?.sendNote(noteOn: true, key: 60, velocity: 100)
                }
            } catch {
                print("engine start failed: \(error)")
            }
        }
    }
}

#endif
