//
// Minimal SwiftUI host for an AUv3 Pulp plug-in (issue #250).
//
// Loads the plug-in's audio unit via AVAudioUnitComponentManager,
// instantiates an AVAudioEngine with a sampler source → the Pulp AU
// → output. The view exposes a play/stop button and lists the
// plug-in's parameters via the AVAudioUnit's parameterTree so the
// user can verify the extension loads without opening a full DAW.
//
// Discovery strategy: read the embedded AUv3's exact
// AudioComponentDescription back from the HostApp's own Info.plist
// `AudioComponents[0]` entry, which is generated by
// `pulp_add_ios_host_app()` from the AUv3 extension target's
// type/subtype/manufacturer/version. That makes the picker
// deterministic when more than one Pulp AUv3 is installed on the
// device or simulator — the HostApp will always instantiate the
// extension it ships with, not whatever Pulp AUv3 happens to register
// first.
//
// If the Info.plist `AudioComponents` entry is missing or malformed
// (developer overrode the template without providing the descriptor)
// the host falls back to the previous manufacturer-only filter so the
// template still surfaces a usable plug-in for triage instead of
// failing silently.
//

import SwiftUI
import AVFoundation
import AudioToolbox
import CoreAudioTypes

#if os(iOS) || os(macOS)

@available(iOS 15.0, macOS 12.0, *)
struct ContentView: View {
    @StateObject private var host = PulpAUv3Host()

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            Text(host.componentName ?? "(no Pulp AUv3 found — check Info.plist)")
                .font(.headline)

            HStack(spacing: 12) {
                Button(host.isPlaying ? "Stop" : "Play") {
                    host.toggle()
                }
                .disabled(host.audioUnit == nil)
                .buttonStyle(.borderedProminent)

                if !host.parameters.isEmpty {
                    Text("\(host.parameters.count) parameter(s)")
                        .foregroundStyle(.secondary)
                }
            }

            ForEach(host.parameters, id: \.address) { p in
                HStack {
                    Text(p.displayName).frame(maxWidth: .infinity, alignment: .leading)
                    Slider(
                        value: Binding(
                            get: { Double(p.value) },
                            set: { p.value = AUValue($0) }
                        ),
                        in: Double(p.minValue)...Double(p.maxValue)
                    )
                    Text(String(format: "%.2f", p.value))
                        .frame(width: 56, alignment: .trailing)
                        .monospacedDigit()
                }
            }

            Spacer()
        }
        .padding()
        .onAppear {
            host.discover()
            // Auto-Play after 1.5s so the audio path lights up without a
            // tap — useful for `simctl io booted recordVideo` smoke runs.
            DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
                if !host.isPlaying && host.audioUnit != nil { host.toggle() }
            }
        }
    }
}

@available(iOS 15.0, macOS 12.0, *)
@MainActor
final class PulpAUv3Host: ObservableObject {
    @Published var componentName: String? = nil
    @Published var parameters: [AUParameter] = []
    @Published var isPlaying = false
    var audioUnit: AUAudioUnit?

    // Pulp manufacturer code: 'Pulp' = 0x50756C70. Used as a
    // last-resort fallback when the HostApp Info.plist doesn't carry
    // an `AudioComponents[0]` entry to disambiguate.
    private let pulpManufacturerCode: OSType = 0x50_75_6C_70

    private let engine = AVAudioEngine()
    private var node: AVAudioUnit?
    private var midiBlock: AUScheduleMIDIEventBlock?

    // Read the embedded AUv3 extension's AudioComponentDescription back
    // from the HostApp's own Info.plist. `pulp_add_ios_host_app()`
    // mirrors the extension's type/subtype/manufacturer/version four-CCs
    // into `AudioComponents[0]` at configure time, so this is the
    // single source of truth that disambiguates which Pulp AUv3 the
    // HostApp ships with when several Pulp plug-ins are installed on
    // the same device or simulator.
    //
    // Returns nil when the entry is missing or malformed; callers
    // fall back to a manufacturer-only filter in that case so the
    // template still surfaces something for triage instead of going
    // silent.
    static func embeddedDescriptor() -> AudioComponentDescription? {
        guard let entries = Bundle.main.object(forInfoDictionaryKey: "AudioComponents") as? [[String: Any]],
              let first = entries.first,
              let typeStr = first["type"] as? String,
              let subtypeStr = first["subtype"] as? String,
              let manufacturerStr = first["manufacturer"] as? String,
              let typeCode = fourCC(from: typeStr),
              let subtypeCode = fourCC(from: subtypeStr),
              let manufacturerCode = fourCC(from: manufacturerStr) else {
            return nil
        }
        var desc = AudioComponentDescription()
        desc.componentType = typeCode
        desc.componentSubType = subtypeCode
        desc.componentManufacturer = manufacturerCode
        desc.componentFlags = 0
        desc.componentFlagsMask = 0
        return desc
    }

    // Convert a four-character code string ("aumu", "PsSn", "Pulp")
    // into the OSType the Audio Unit APIs expect. Returns nil for
    // anything that isn't exactly four ASCII bytes.
    private static func fourCC(from s: String) -> OSType? {
        let bytes = Array(s.utf8)
        guard bytes.count == 4 else { return nil }
        return (OSType(bytes[0]) << 24) | (OSType(bytes[1]) << 16) | (OSType(bytes[2]) << 8) | OSType(bytes[3])
    }

    // Inverse of fourCC(from:) for log lines. Renders four bytes of an
    // OSType back as the ASCII four-character code the AU APIs use.
    fileprivate func fourCCString(_ code: OSType) -> String {
        let bytes: [UInt8] = [
            UInt8((code >> 24) & 0xff),
            UInt8((code >> 16) & 0xff),
            UInt8((code >> 8) & 0xff),
            UInt8(code & 0xff),
        ]
        if let s = String(bytes: bytes, encoding: .ascii) { return s }
        return String(format: "0x%08x", code)
    }

    func discover() {
        // Prefer the exact descriptor mirrored from the embedded AUv3
        // (HostApp Info.plist → AudioComponents[0]) so the picker is
        // deterministic across installed Pulp plug-ins. Fall back to
        // a manufacturer-only filter when the entry is missing — that
        // path preserves the previous behaviour for debugging-only
        // HostApps that strip the AudioComponents key.
        let manager = AVAudioUnitComponentManager.shared()
        let allUnits = manager.components(matching: AudioComponentDescription())

        let embedded = Self.embeddedDescriptor()
        let pulpUnits: [AVAudioUnitComponent]
        let matchMode: String
        if let target = embedded {
            pulpUnits = allUnits.filter { c in
                let d = c.audioComponentDescription
                return d.componentType == target.componentType
                    && d.componentSubType == target.componentSubType
                    && d.componentManufacturer == target.componentManufacturer
            }
            matchMode = String(
                format: "exact descriptor type=%@ subtype=%@ mfr=%@",
                fourCCString(target.componentType),
                fourCCString(target.componentSubType),
                fourCCString(target.componentManufacturer))
        } else {
            pulpUnits = allUnits.filter { $0.audioComponentDescription.componentManufacturer == pulpManufacturerCode }
            matchMode = "fallback manufacturer-only (no AudioComponents[0] in Info.plist)"
        }

        // PULP_DISCOVER prints are deliberate triage helpers — keep them.
        // When the audio path silently fails, grep `PULP_` in the launch
        // log to identify which step in the chain broke. See
        // `.agents/skills/auv3/SKILL.md` "iOS AUv3 diagnostic recipe".
        print("PULP_DISCOVER_ALL: \(allUnits.count) total AUv3 components on this system")
        print("PULP_DISCOVER_MODE: \(matchMode)")
        print("PULP_DISCOVER: matching Pulp components=\(pulpUnits.count)")
        for c in pulpUnits {
            print("PULP_DISCOVER:   - name=\(c.name) type=\(c.typeName) mfr=\(c.manufacturerName)")
        }

        guard let first = pulpUnits.first else {
            print("PULP_DISCOVER: no matching Pulp AUv3 found — extension may have failed to register, or HostApp Info.plist AudioComponents[0] does not match the embedded .appex")
            return
        }
        let firstName = first.name
        Task { @MainActor in self.componentName = "Found: \(firstName)" }

        let desc = first.audioComponentDescription

        // iOS cannot load AUv3 extensions in-process; must use
        // .loadOutOfProcess. The default `[]` returns OSStatus 4
        // ("Exec format" / instantiate failed). See Apple's
        // "Incorporating Audio Effects and Instruments" sample.
        #if os(iOS)
        let instOptions: AudioComponentInstantiationOptions = .loadOutOfProcess
        #else
        let instOptions: AudioComponentInstantiationOptions = []
        #endif

        AVAudioUnit.instantiate(with: desc, options: instOptions) { [weak self] node, error in
            if let err = error { print("PULP_INSTANTIATE_ERROR: \(err)") }
            guard let self = self, let node = node, error == nil else {
                print("PULP_INSTANTIATE: bailed (node=\(String(describing: node)) error=\(String(describing: error)))")
                return
            }
            Task { @MainActor in
                self.node = node
                self.audioUnit = node.auAudioUnit
                self.componentName = node.auAudioUnit.componentName
                print("PULP_INSTANTIATE_OK: \(node.auAudioUnit.componentName ?? "(nil)")")
                if let tree = node.auAudioUnit.parameterTree {
                    self.parameters = tree.allParameters
                }
                self.engine.attach(node)

                // Effects need a source feeding them — otherwise they
                // silently process zeros. Instruments (aumu) drive
                // themselves via MIDI events sent below in toggle().
                if desc.componentType != kAudioUnitType_MusicDevice {
                    self.engine.connect(self.engine.inputNode, to: node, format: nil)
                }
                self.engine.connect(node, to: self.engine.mainMixerNode, format: nil)

                // For an instrument (aumu), wire a MIDI event block so
                // toggle() can send a sustained note. Pattern from
                // Apple's SimplePlayEngine.InstrumentPlayer.
                if desc.componentType == kAudioUnitType_MusicDevice {
                    self.midiBlock = node.auAudioUnit.scheduleMIDIEventBlock
                    print("PULP_MIDI_BLOCK: \(self.midiBlock != nil ? "ready" : "unavailable")")
                }
            }
        }
    }

    func sendNote(noteOn: Bool, key: UInt8 = 60, velocity: UInt8 = 100) {
        guard let block = midiBlock else { print("PULP_NOTE: no midiBlock"); return }
        let status: UInt8 = noteOn ? 0x90 : 0x80
        let vel: UInt8 = noteOn ? velocity : 0
        let bytes = UnsafeMutablePointer<UInt8>.allocate(capacity: 3)
        bytes[0] = status; bytes[1] = key; bytes[2] = vel
        block(AUEventSampleTimeImmediate, 0, 3, bytes)
        bytes.deallocate()
        print("PULP_NOTE: \(noteOn ? "ON" : "OFF") key=\(key) vel=\(vel)")
    }

    func toggle() {
        if isPlaying {
            sendNote(noteOn: false)
            engine.stop()
            isPlaying = false
        } else {
            do {
                try engine.start()
                isPlaying = true
                // Trigger a sustained C4 (note 60) for the instrument
                // path so we hear something when Play is tapped. Effects
                // don't need MIDI — they're fed by inputNode in discover().
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) { [weak self] in
                    self?.sendNote(noteOn: true, key: 60, velocity: 100)
                }
            } catch {
                print("engine start failed: \(error)")
            }
        }
    }
}

#endif
