#!/usr/bin/env python3
"""
Generate or verify auto-injected tables inside docs/reference/capabilities.md.

Auto-injected regions are delimited by fenced comments:

    <!-- generated:start id=<block_id> -->
    ...content will be overwritten...
    <!-- generated:end id=<block_id> -->

Modes:
  generate   rewrite the file in place with fresh content (default)
  check      compare in-place content against fresh content; exit 1 on diff

Registered generators (`id:`):
  - limitations  — renders the `limitations:` block from
                   docs/status/support-matrix.yaml (workstream 08 slice 8.5)

Part of workstream 08 slice 8.3.
"""
from __future__ import annotations

import argparse
import io
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
CAPABILITIES_PATH = REPO_ROOT / "docs" / "reference" / "capabilities.md"
LIST_LIMITATIONS = REPO_ROOT / "tools" / "list_limitations.py"

START = re.compile(r"<!--\s*generated:start\s+id=([A-Za-z0-9_\-]+)\s*-->")
END = re.compile(r"<!--\s*generated:end\s+id=([A-Za-z0-9_\-]+)\s*-->")


def render_limitations() -> str:
    if not LIST_LIMITATIONS.exists():
        return "_(limitations generator missing)_\n"
    try:
        result = subprocess.run(
            ["python3", str(LIST_LIMITATIONS)],
            capture_output=True, text=True, check=False,
        )
    except Exception as e:
        return f"_(limitations generator failed: {e})_\n"
    if result.returncode != 0:
        # Non-fatal — surface the stderr inside the region so reviewers notice.
        return (
            f"_(limitations generator exited {result.returncode})_\n\n"
            f"```\n{result.stderr.strip()}\n```\n"
        )
    # Strip the leading "<!-- generated by ... -->" line; we already wrap the
    # region with generated:start / generated:end markers.
    lines = result.stdout.splitlines()
    if lines and lines[0].startswith("<!-- generated"):
        lines = lines[1:]
    body = "\n".join(lines).strip()
    if not body:
        return "_(no limitations declared in support-matrix.yaml)_\n"
    return body + "\n"


GENERATORS = {
    "limitations": render_limitations,
}


def rewrite(text: str) -> str:
    out = io.StringIO()
    lines = text.splitlines(keepends=True)
    i = 0
    while i < len(lines):
        line = lines[i]
        m = START.search(line)
        if not m:
            out.write(line)
            i += 1
            continue
        block_id = m.group(1)
        out.write(line)
        # Skip through to the matching end marker
        j = i + 1
        while j < len(lines) and not END.search(lines[j]):
            j += 1
        # Produce fresh content
        gen = GENERATORS.get(block_id)
        if gen is None:
            out.write(f"_(unknown generator id='{block_id}')_\n")
        else:
            out.write(gen())
        if j < len(lines):
            out.write(lines[j])
            i = j + 1
        else:
            # Missing end marker — stop here and append one for sanity
            out.write(f"<!-- generated:end id={block_id} -->\n")
            i = len(lines)
    return out.getvalue()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("mode", nargs="?", choices=("generate", "check"), default="generate")
    args = ap.parse_args()
    try:
        current = CAPABILITIES_PATH.read_text()
    except Exception as e:
        sys.stderr.write(f"Failed to read {CAPABILITIES_PATH}: {e}\n")
        return 2

    fresh = rewrite(current)

    if args.mode == "check":
        if fresh == current:
            print("docs-generate: OK")
            return 0
        print("docs-generate: DRIFT DETECTED")
        print("Run `python3 tools/docs_generate.py generate` to refresh "
              "capabilities.md and commit the result.")
        # Short unified diff sample
        import difflib
        diff = list(difflib.unified_diff(
            current.splitlines(), fresh.splitlines(),
            fromfile="capabilities.md (current)",
            tofile="capabilities.md (regenerated)",
            lineterm="",
        ))
        for line in diff[:80]:
            print(line)
        return 1

    if fresh != current:
        CAPABILITIES_PATH.write_text(fresh)
        print("docs-generate: rewrote docs/reference/capabilities.md")
    else:
        print("docs-generate: no changes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
