#!/usr/bin/env python3
"""
Render the `limitations:` block from docs/status/support-matrix.yaml as a
Markdown table suitable for inclusion in docs/reference/capabilities.md.

Part of workstream 08 slice 8.5. The auto-inject flow lands in slice 8.3
(generated tables); for now this script prints to stdout.

Also validates that every capability path referenced under `limitations:`
resolves to a real entry in the matrix. Exit 1 on unresolved paths.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MATRIX_PATH = REPO_ROOT / "docs" / "status" / "support-matrix.yaml"


def extract_limitations(text: str) -> list[tuple[str, list[dict[str, str]]]]:
    """Return [(capability_path, [{text, tracked_in}, ...]), ...]."""
    m = re.search(
        r"^limitations:\s*\n(.*?)(?=^\S|\Z)",
        text, flags=re.MULTILINE | re.DOTALL,
    )
    if not m:
        return []
    block = m.group(1)
    entries: list[tuple[str, list[dict[str, str]]]] = []
    current_path: str | None = None
    current_items: list[dict[str, str]] = []

    def flush():
        if current_path is not None:
            entries.append((current_path, current_items[:]))

    for line in block.splitlines():
        if line.lstrip().startswith("#"):
            continue
        if not line.strip():
            continue
        mk = re.match(r"^  ([A-Za-z0-9_.-]+):\s*$", line)
        if mk:
            flush()
            current_path = mk.group(1)
            current_items = []
            continue
        mt = re.match(r'^    -\s*text:\s*"(.*)"\s*$', line)
        if mt and current_path is not None:
            current_items.append({"text": mt.group(1), "tracked_in": ""})
            continue
        mtr = re.match(r'^      tracked_in:\s*"(.*)"\s*$', line)
        if mtr and current_items:
            current_items[-1]["tracked_in"] = mtr.group(1)
    flush()
    return entries


def capability_exists(text: str, path: str) -> bool:
    """Best-effort check that a dotted path resolves to a YAML key."""
    parts = path.split(".")
    # Walk top-down looking for each key at successively deeper indent.
    expected_indent = 0
    i = 0
    lines = text.splitlines()
    idx = 0
    while i < len(parts):
        key = parts[i]
        pat = re.compile(r"^" + (" " * expected_indent) + re.escape(key) + r":")
        found = False
        while idx < len(lines):
            if pat.match(lines[idx]):
                found = True
                idx += 1
                break
            idx += 1
        if not found:
            return False
        expected_indent += 2
        i += 1
    return True


def main() -> int:
    try:
        text = MATRIX_PATH.read_text()
    except Exception as e:
        sys.stderr.write(f"Failed to read {MATRIX_PATH}: {e}\n")
        return 2

    entries = extract_limitations(text)
    if not entries:
        print("No limitations: block found in support-matrix.yaml.")
        return 0

    # Validate paths
    unresolved = [p for p, _ in entries if not capability_exists(text, p)]
    if unresolved:
        sys.stderr.write("Unresolved capability paths in limitations:\n")
        for p in unresolved:
            sys.stderr.write(f"  - {p}\n")
        return 1

    total = sum(len(items) for _, items in entries)
    print(f"<!-- generated by tools/list_limitations.py -->")
    print(f"### Known limitations ({total} items across {len(entries)} capabilities)")
    print()
    print("| Capability | Limitation | Tracked in |")
    print("|---|---|---|")
    for path, items in entries:
        for item in items:
            tracked = item.get("tracked_in", "")
            link = f"[link]({tracked})" if tracked else "—"
            print(f"| `{path}` | {item['text']} | {link} |")
    return 0


if __name__ == "__main__":
    sys.exit(main())
