#!/usr/bin/env python3
"""Unit tests for tools/list_limitations.py."""

from __future__ import annotations

import contextlib
import importlib.util
import io
import pathlib
import runpy
import sys
import tempfile
import unittest
from unittest import mock


SCRIPT = pathlib.Path(__file__).parent / "list_limitations.py"
spec = importlib.util.spec_from_file_location("list_limitations", SCRIPT)
assert spec and spec.loader
ll = importlib.util.module_from_spec(spec)
sys.modules["list_limitations"] = ll
spec.loader.exec_module(ll)


MATRIX = """
runtime:
  audio:
    hosting:
      status: partial
  midi:
    status: stable

limitations:
  # comments and blanks are ignored

  runtime.audio.hosting:
    - text: "AUv3 sidechain discovery is incomplete."
      tracked_in: "https://example.test/issues/123"
    - text: "LV2 scanning is experimental."
  runtime.midi:
    - text: "UMP profile negotiation is simulated."
      tracked_in: ""
"""


class ExtractLimitationsTests(unittest.TestCase):
    def test_extract_limitations_parses_items_and_optional_tracking(self) -> None:
        entries = ll.extract_limitations(MATRIX)

        self.assertEqual(
            entries,
            [
                (
                    "runtime.audio.hosting",
                    [
                        {
                            "text": "AUv3 sidechain discovery is incomplete.",
                            "tracked_in": "https://example.test/issues/123",
                        },
                        {
                            "text": "LV2 scanning is experimental.",
                            "tracked_in": "",
                        },
                    ],
                ),
                (
                    "runtime.midi",
                    [
                        {
                            "text": "UMP profile negotiation is simulated.",
                            "tracked_in": "",
                        },
                    ],
                ),
            ],
        )

    def test_extract_limitations_returns_empty_when_block_missing(self) -> None:
        self.assertEqual(ll.extract_limitations("runtime:\n  midi:\n"), [])

    def test_extract_limitations_ignores_orphaned_tracking_rows(self) -> None:
        matrix = """
runtime:
  midi:
    status: stable

limitations:
  runtime.midi:
      tracked_in: "https://example.test/issues/orphaned"
"""

        self.assertEqual(ll.extract_limitations(matrix), [("runtime.midi", [])])

    def test_extract_limitations_accepts_hyphenated_capability_paths(self) -> None:
        matrix = """
runtime:
  audio-engine:
    status: partial

limitations:
  runtime.audio-engine:
    - text: "Hyphenated capability path."
"""

        self.assertEqual(
            ll.extract_limitations(matrix),
            [
                (
                    "runtime.audio-engine",
                    [{"text": "Hyphenated capability path.", "tracked_in": ""}],
                )
            ],
        )


class CapabilityPathTests(unittest.TestCase):
    def test_capability_exists_walks_nested_yaml_keys(self) -> None:
        self.assertTrue(ll.capability_exists(MATRIX, "runtime.audio.hosting"))
        self.assertTrue(ll.capability_exists(MATRIX, "runtime.midi"))

    def test_capability_exists_rejects_missing_or_misordered_paths(self) -> None:
        self.assertFalse(ll.capability_exists(MATRIX, "runtime.audio.render"))
        self.assertFalse(ll.capability_exists(MATRIX, "audio.runtime.hosting"))


class MainTests(unittest.TestCase):
    def _run_main(self, matrix_text: str | None) -> tuple[int, str, str]:
        stdout = io.StringIO()
        stderr = io.StringIO()
        with tempfile.TemporaryDirectory() as td:
            matrix_path = pathlib.Path(td) / "support-matrix.yaml"
            if matrix_text is not None:
                matrix_path.write_text(matrix_text, encoding="utf-8")
            with (
                mock.patch.object(ll, "MATRIX_PATH", matrix_path),
                contextlib.redirect_stdout(stdout),
                contextlib.redirect_stderr(stderr),
            ):
                rc = ll.main()
        return rc, stdout.getvalue(), stderr.getvalue()

    def test_main_renders_markdown_table(self) -> None:
        rc, stdout, stderr = self._run_main(MATRIX)

        self.assertEqual(rc, 0)
        self.assertEqual(stderr, "")
        self.assertIn("<!-- generated by tools/list_limitations.py -->", stdout)
        self.assertIn("Known limitations (3 items across 2 capabilities)", stdout)
        self.assertIn(
            "| `runtime.audio.hosting` | AUv3 sidechain discovery is incomplete. | "
            "[link](https://example.test/issues/123) |",
            stdout,
        )
        self.assertIn(
            "| `runtime.audio.hosting` | LV2 scanning is experimental. | — |",
            stdout,
        )

    def test_main_reports_no_limitations_block(self) -> None:
        rc, stdout, stderr = self._run_main("runtime:\n  midi:\n    status: stable\n")

        self.assertEqual(rc, 0)
        self.assertEqual(stderr, "")
        self.assertEqual(stdout, "No limitations: block found in support-matrix.yaml.\n")

    def test_main_reports_unresolved_paths(self) -> None:
        rc, stdout, stderr = self._run_main(
            MATRIX + "\n  runtime.missing:\n    - text: \"Missing.\"\n"
        )

        self.assertEqual(rc, 1)
        self.assertEqual(stdout, "")
        self.assertIn("Unresolved capability paths", stderr)
        self.assertIn("runtime.missing", stderr)

    def test_main_reports_read_error(self) -> None:
        rc, stdout, stderr = self._run_main(None)

        self.assertEqual(rc, 2)
        self.assertEqual(stdout, "")
        self.assertIn("Failed to read", stderr)

    def test_script_entrypoint_exits_with_main_status(self) -> None:
        stdout = io.StringIO()
        with (
            mock.patch.object(pathlib.Path, "read_text", return_value=MATRIX),
            contextlib.redirect_stdout(stdout),
            self.assertRaises(SystemExit) as raised,
        ):
            runpy.run_path(str(SCRIPT), run_name="__main__")

        self.assertEqual(raised.exception.code, 0)
        self.assertIn(
            "Known limitations (3 items across 2 capabilities)",
            stdout.getvalue(),
        )


if __name__ == "__main__":
    unittest.main(verbosity=2)
