// {{PLUGIN_NAME}} — UI Script
// Generated by: pulp create --template gain
// Edit this file and save — hot-reload updates the UI instantly.

// Root layout
const root = createCol("root");
setFlex("root", "padding_top", 24);
setFlex("root", "padding_left", 24);
setFlex("root", "padding_right", 24);
setFlex("root", "padding_bottom", 24);
setFlex("root", "gap", 20);
setFlex("root", "align_items", "center");
setBackground("root", "#1a1a2e");

// Title
createLabel("title", "{{PLUGIN_NAME}}", "root");
setFontSize("title", 20);
setFontWeight("title", 700);
setTextColor("title", "#e0e0e0");
setTextAlign("title", "center");

// Gain knob section
const knobCol = createCol("knob-col", "root");
setFlex("knob-col", "align_items", "center");
setFlex("knob-col", "gap", 8);

createKnob("gain", "knob-col");
setFlex("gain", "width", 80);
setFlex("gain", "height", 80);
setValue("gain", getParam("Gain"));
setLabel("gain", "Gain");

// Value readout
createLabel("readout", "0.0 dB", "knob-col");
setFontSize("readout", 14);
setTextColor("readout", "#888888");
setTextAlign("readout", "center");

on("gain", "change", (v) => {
    setParam("Gain", v);
    const db = -60 + v * 84; // map 0..1 to -60..+24 dB
    setText("readout", db.toFixed(1) + " dB");
});

// Bypass toggle
const bypassRow = createRow("bypass-row", "root");
setFlex("bypass-row", "align_items", "center");
setFlex("bypass-row", "gap", 8);

createToggle("bypass", "bypass-row");
setValue("bypass", getParam("Bypass"));

createLabel("bypass-lbl", "Bypass", "bypass-row");
setFontSize("bypass-lbl", 13);
setTextColor("bypass-lbl", "#999999");

on("bypass", "toggle", (v) => {
    setParam("Bypass", v ? 1.0 : 0.0);
    setOpacity("gain", v ? 0.4 : 1.0);
});
