#pragma once

// Convenience header — includes all pulp-signal DSP utilities
#include <pulp/signal/smoothed_value.hpp>
#include <pulp/signal/adsr.hpp>
#include <pulp/signal/biquad.hpp>
#include <pulp/signal/oscillator.hpp>
#include <pulp/signal/delay_line.hpp>
#include <pulp/signal/gain.hpp>
#include <pulp/signal/compressor.hpp>
#include <pulp/signal/svf.hpp>
#include <pulp/signal/waveshaper.hpp>
#include <pulp/signal/oversampling.hpp>
#include <pulp/signal/noise_gate.hpp>
#include <pulp/signal/panner.hpp>
#include <pulp/signal/chorus.hpp>
#include <pulp/signal/phaser.hpp>
#include <pulp/signal/reverb.hpp>
#include <pulp/signal/ladder_filter.hpp>
#include <pulp/signal/linkwitz_riley.hpp>
#include <pulp/signal/windowing.hpp>
#include <pulp/signal/fft.hpp>
#include <pulp/signal/fir_filter.hpp>
#include <pulp/signal/ballistics_filter.hpp>
#include <pulp/signal/log_ramped_value.hpp>
#include <pulp/signal/processor_chain.hpp>
#include <pulp/signal/lookup_table.hpp>
#include <pulp/signal/tpt_filter.hpp>
#include <pulp/signal/interpolator.hpp>
#include <pulp/signal/filter_design.hpp>
#include <pulp/signal/fast_math.hpp>
#include <pulp/signal/poly_math.hpp>
#include <pulp/signal/stft.hpp>
#include <pulp/signal/spectrogram.hpp>
#include <pulp/signal/multi_channel_meter.hpp>
